from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Phase5ContractGroup:
    group_key: str
    title: str
    description: str
    route_prefix: str
    critical_endpoints: tuple[str, ...]
    response_contract_fields: tuple[str, ...]
    invariants: dict[str, bool]
    caveats: tuple[str, ...]

    def _read_write_semantics(self) -> dict[str, object]:
        read_endpoints = [ep for ep in self.critical_endpoints if ep.startswith("GET ")]
        write_endpoints = [
            ep
            for ep in self.critical_endpoints
            if ep.startswith("POST ") or ep.startswith("PATCH ") or ep.startswith("PUT ") or ep.startswith("DELETE ")
        ]
        return {
            "read_endpoints": read_endpoints,
            "write_endpoints": write_endpoints,
            "read_only_endpoints_write_no_audit": bool(self.invariants.get("read_only_endpoint_no_audit", False)),
            "persisted_writes_audited": bool(self.invariants.get("persisted_action_audited", False)),
        }

    def as_dict(self) -> dict:
        return {
            "group_key": self.group_key,
            "title": self.title,
            "description": self.description,
            "route_prefix": self.route_prefix,
            "critical_endpoints": list(self.critical_endpoints),
            "endpoints": list(self.critical_endpoints),
            "response_contract_fields": list(self.response_contract_fields),
            "protected_fields": list(self.response_contract_fields),
            "read_write_semantics": self._read_write_semantics(),
            "invariants": self.invariants,
            "caveats": list(self.caveats),
            "non_execution_guarantee": "This contract surface is non-executing and does not run automation.",
            "no_legal_regulatory_determination": (
                "This contract surface does not make legal or regulatory determinations."
            ),
        }


PHASE5_CONTRACTS: tuple[Phase5ContractGroup, ...] = (
    Phase5ContractGroup(
        group_key="ai_system_inventory",
        title="AI System Inventory",
        description="Tenant-scoped AI system CRUD and archive lifecycle.",
        route_prefix="/api/v1/ai-systems",
        critical_endpoints=("POST /ai-systems", "GET /ai-systems", "POST /ai-systems/{ai_system_id}/archive"),
        response_contract_fields=("id", "organization_id", "name", "system_type", "lifecycle_status", "archived_at"),
        invariants={"tenant_scoped": True, "archived_records_not_hard_deleted": True, "persisted_action_audited": True},
        caveats=("Inventory metadata only.",),
    ),
    Phase5ContractGroup(
        group_key="governance_reviews",
        title="Governance Reviews",
        description="Manual review lifecycle and outcomes.",
        route_prefix="/api/v1/ai-systems/{ai_system_id}/governance-reviews",
        critical_endpoints=("POST /governance-reviews", "POST /{review_id}/complete", "GET /governance-summary"),
        response_contract_fields=("id", "status", "outcome", "due_at", "started_at", "completed_at"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Manual governance only.",),
    ),
    Phase5ContractGroup(
        group_key="governance_attestations",
        title="Governance Attestations",
        description="Internal attestation integrity records and verification.",
        route_prefix="/api/v1/ai-systems/{ai_system_id}/governance-reviews/{review_id}/attestations",
        critical_endpoints=("POST /attestations", "POST /attestations/{attestation_id}/verify"),
        response_contract_fields=("content_sha256", "internal_signature", "signature_algorithm", "caveat"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "internal_signature_not_legal_signature": True},
        caveats=("Internal integrity only.",),
    ),
    Phase5ContractGroup(
        group_key="review_scheduling",
        title="Review Scheduling",
        description="Due dates, queue, deterministic schedule evaluation.",
        route_prefix="/api/v1/ai-governance",
        critical_endpoints=("POST /governance-reviews/{review_id}/schedule", "POST /review-queue/evaluate-schedules"),
        response_contract_fields=("due_at", "is_overdue", "event_type", "status"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("No autonomous scheduler.",),
    ),
    Phase5ContractGroup(
        group_key="recurrence_templates",
        title="Recurrence Templates",
        description="Manual recurrence templates and plan runs.",
        route_prefix="/api/v1/ai-governance/review-recurrence-templates",
        critical_endpoints=("POST /review-recurrence-templates", "POST /{template_id}/generate-plan"),
        response_contract_fields=("template_id", "dry_run", "planned_reviews", "skipped_reviews", "caveat"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Human-triggered only.",),
    ),
    Phase5ContractGroup(
        group_key="sequence_packs",
        title="Sequence Packs",
        description="Manual multi-step rollout sequencing.",
        route_prefix="/api/v1/ai-governance/review-sequence-packs",
        critical_endpoints=("POST /review-sequence-packs", "POST /{pack_id}/generate-sequence"),
        response_contract_fields=("sequence_pack_id", "planned_reviews", "skipped_reviews", "guardrail_results", "caveat"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Operator-triggered only.",),
    ),
    Phase5ContractGroup(
        group_key="guardrail_freeze_windows",
        title="Guardrail Freeze Windows",
        description="Deterministic freeze-window guardrails and precedence.",
        route_prefix="/api/v1/ai-governance/guardrails/freeze-windows",
        critical_endpoints=("POST /guardrails/freeze-windows", "POST /guardrails/check", "POST /guardrails/resolve-conflicts"),
        response_contract_fields=(
            "matching_freeze_windows",
            "resolution",
            "primary_blocking_window_id",
            "override_allowed",
            "precedence_order",
        ),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Deterministic operator controls.",),
    ),
    Phase5ContractGroup(
        group_key="guardrail_policy_sets",
        title="Guardrail Policy Sets",
        description="Policy-set and active-version profile management.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-sets",
        critical_endpoints=("POST /policy-sets", "POST /policy-sets/{id}/versions", "POST /policy-sets/{id}/versions/{version_id}/activate"),
        response_contract_fields=("policy_set_id", "version_number", "status", "profile_json", "active_version_id"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Configuration profiles only.",),
    ),
    Phase5ContractGroup(
        group_key="guardrail_policy_assignments",
        title="Guardrail Policy Assignments",
        description="Deterministic default policy mapping and resolve source.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-assignments",
        critical_endpoints=("POST /policy-assignments", "POST /policy-assignments/resolve"),
        response_contract_fields=("resolved_policy_set_id", "resolution_source", "assignment_id", "precedence_trace"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Explicit request takes precedence.",),
    ),
    Phase5ContractGroup(
        group_key="policy_resolution_simulations",
        title="Policy Resolution Simulations",
        description="Read-only/batch policy resolution simulation with optional persistence.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/simulate",
        critical_endpoints=("POST /policy-resolution/simulate", "GET /policy-resolution/simulation-reports"),
        response_contract_fields=("contexts", "policy_resolution", "guardrail_resolution", "precedence_trace", "persisted"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Read-only unless persist_report=true.",),
    ),
    Phase5ContractGroup(
        group_key="policy_resolution_diffs",
        title="Policy Resolution Diffs",
        description="Deterministic comparison between persisted simulation reports.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/simulation-reports/diff",
        critical_endpoints=("POST /simulation-reports/diff", "GET /simulation-diff-reports/{id}"),
        response_contract_fields=(
            "context_match_strategy",
            "added_contexts_count",
            "changed_contexts_count",
            "context_diffs",
            "reason_code_summary",
        ),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Read-only unless persist_diff=true.",),
    ),
    Phase5ContractGroup(
        group_key="gating_profiles",
        title="Policy Diff Gating Profiles",
        description="Reason-code gating profile configuration and classify endpoint.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-profiles",
        critical_endpoints=("POST /diff-gating-profiles", "POST /simulation-diff-reports/{id}/classify"),
        response_contract_fields=("max_severity", "review_required", "reason_code_count", "severity_summary"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "read_only_endpoint_no_audit": True},
        caveats=("Classification only.",),
    ),
    Phase5ContractGroup(
        group_key="gating_compare_reports",
        title="Policy Diff Gating Compare",
        description="Baseline compare for policy-diff gating reports.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-reports/compare",
        critical_endpoints=("POST /diff-gating-reports/compare", "GET /diff-gating-compare-reports/{id}"),
        response_contract_fields=("severity_direction", "review_required_changed", "reason_code_changes", "aggregate_deltas"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Read-only unless persist_compare=true.",),
    ),
    Phase5ContractGroup(
        group_key="gating_compare_presets",
        title="Policy Diff Gating Compare Presets",
        description="Reusable interpretation presets for compare outputs.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-presets",
        critical_endpoints=("POST /diff-gating-compare-presets", "POST /diff-gating-compare-presets/{id}/evaluate"),
        response_contract_fields=("interpretation_band", "review_required", "watched_reason_codes_hit_count", "matched_rules"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Interpretation helpers only.",),
    ),
    Phase5ContractGroup(
        group_key="gating_compare_preset_versions",
        title="Policy Diff Gating Compare Preset Versions",
        description="Immutable version snapshots and pinning for compare presets.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-presets/{preset_id}/versions",
        critical_endpoints=("POST /versions", "POST /versions/{version_id}/activate", "POST /pin-version"),
        response_contract_fields=(
            "preset_version_id",
            "preset_version_number",
            "preset_snapshot_json",
            "version_resolution_source",
            "explicit_version_override_used",
        ),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "archived_records_not_hard_deleted": True},
        caveats=("Immutable snapshots.",),
    ),
    Phase5ContractGroup(
        group_key="gating_compare_preset_assignments",
        title="Policy Diff Gating Compare Preset Assignments",
        description="Default preset assignment resolution and diagnostics.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /.../resolve", "POST /.../evaluate-default", "POST /.../coverage-diagnostics"),
        response_contract_fields=("resolved_preset_id", "resolution_source", "precedence_trace", "diagnostics", "severity"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Explicit preset overrides mapped default.",),
    ),
    Phase5ContractGroup(
        group_key="preset_assignment_diagnostics",
        title="Preset Assignment Diagnostics",
        description="Read-only coverage and health diagnostics for preset assignments.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /coverage-diagnostics", "GET /health-diagnostics", "GET /coverage-summary"),
        response_contract_fields=("context_count", "resolved_contexts_count", "contexts", "aggregate_diagnostics", "caveat"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True},
        caveats=("Read-only diagnostics.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_reports",
        title="Diagnostic Reports",
        description="Persisted diagnostic snapshots and diffability.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments/diagnostic-reports",
        critical_endpoints=("POST /coverage-diagnostics", "GET /diagnostic-reports/{id}", "POST /diagnostic-reports/diff"),
        response_contract_fields=("input_contexts_json", "result_json", "context_count", "critical_contexts_count", "status"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True},
        caveats=("Immutable snapshots.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_exports",
        title="Diagnostic Exports",
        description="JSON-only persisted exports with integrity metadata.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments/diagnostic-exports",
        critical_endpoints=("POST /diagnostic-reports/{id}/export", "POST /diagnostic-exports/{id}/verify", "POST /diagnostic-exports/{id}/revoke"),
        response_contract_fields=(
            "canonical_payload_sha256",
            "internal_signature",
            "signature_algorithm",
            "signing_key_id",
            "status",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "no_external_storage": True,
            "internal_signature_not_legal_signature": True,
        },
        caveats=("JSON-only export.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diffs",
        title="Diagnostic Export Diffs",
        description="Deterministic JSON-path diffs between persisted exports.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments/diagnostic-exports/diff",
        critical_endpoints=("POST /diagnostic-exports/diff", "GET /diagnostic-export-diff-reports/{id}"),
        response_contract_fields=("payload_hash_changed", "path_diffs", "added_paths_count", "changed_paths_count"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Read-only unless persist_diff=true.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_reason_codes",
        title="Diagnostic Export Diff Reason Codes",
        description="Normalized reason-code catalog and summary aggregates for export diffs.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=(
            "GET /diagnostic-export-diff-reason-codes",
            "POST /diagnostic-exports/diff",
            "GET /diagnostic-export-diff-summary",
        ),
        response_contract_fields=("reason_code_summary", "reason_code_count", "top_reason_codes", "reason_codes"),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True},
        caveats=("Reason codes are deterministic labels only.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_gating",
        title="Diagnostic Export Diff Gating",
        description="Reason-code-based classification for diagnostic export diff reports.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /diagnostic-export-diff-gating-profiles", "POST /diagnostic-export-diff-reports/{id}/classify"),
        response_contract_fields=("max_severity", "review_required", "reason_code_classifications", "severity_summary"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "read_only_endpoint_no_audit": True},
        caveats=("Classification only.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_gating_compare",
        title="Diagnostic Export Diff Gating Compare",
        description="Baseline compare mode for diagnostic export-diff gating reports.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /diagnostic-export-diff-gating-reports/compare", "GET /diagnostic-export-diff-gating-compare-summary"),
        response_contract_fields=(
            "max_severity_drift",
            "review_required_drift",
            "reason_code_changes_count",
            "added_reason_codes",
            "changed_reason_codes",
        ),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Read-only unless persist_compare=true.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_gating_compare_presets",
        title="Diagnostic Export Diff Gating Compare Presets",
        description="Reusable interpretation presets for compare outputs.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=(
            "POST /diagnostic-export-diff-gating-compare-presets",
            "POST /diagnostic-export-diff-gating-compare-reports/{id}/evaluate-preset",
        ),
        response_contract_fields=("interpretation_band", "review_required", "matched_rules", "preset_id"),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "read_only_endpoint_no_audit": True},
        caveats=("Interpretation helpers only.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_gating_compare_preset_versions",
        title="Diagnostic Export Diff Gating Compare Preset Versions",
        description="Immutable version snapshots and pinning for compare interpretation presets.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /.../versions", "POST /.../versions/{version_id}/activate", "POST /.../pin-version"),
        response_contract_fields=(
            "preset_version_id",
            "preset_version_number",
            "preset_snapshot_used",
            "version_resolution_source",
            "pinned_version_id",
        ),
        invariants={"tenant_scoped": True, "persisted_action_audited": True, "archived_records_not_hard_deleted": True},
        caveats=("Immutable snapshots and deterministic pinning.",),
    ),
    Phase5ContractGroup(
        group_key="diagnostic_export_diff_gating_compare_preset_assignments",
        title="Diagnostic Export Diff Gating Compare Preset Assignments",
        description="Assignment-default resolution for compare interpretation presets and read-only diagnostics.",
        route_prefix="/api/v1/ai-governance/guardrails/policy-resolution/diff-gating-compare-preset-assignments",
        critical_endpoints=("POST /.../resolve", "POST /.../evaluate-default-preset", "POST /.../coverage-diagnostics"),
        response_contract_fields=(
            "preset_resolution",
            "version_resolution_source",
            "resolved_preset_id",
            "resolved_assignment_id",
            "precedence_trace",
            "diagnostics",
        ),
        invariants={"tenant_scoped": True, "read_only_endpoint_no_audit": True, "persisted_action_audited": True},
        caveats=("Deterministic defaults; explicit preset wins.",),
    ),
)

PHASE6_CONTRACTS: tuple[Phase5ContractGroup, ...] = (
    Phase5ContractGroup(
        group_key="ai_risk_assessments",
        title="AI Risk Assessments",
        description="Manual-first AI system risk assessments with immutable snapshots and lifecycle actions.",
        route_prefix="/api/v1/ai-governance/ai-risk",
        critical_endpoints=(
            "POST /ai-risk/assessments",
            "POST /ai-risk/assessments/{assessment_id}/complete",
            "POST /ai-risk/assessments/{assessment_id}/snapshots",
            "GET /ai-risk/assessments/summary",
        ),
        response_contract_fields=(
            "assessment_type",
            "status",
            "scoring_profile_id",
            "scoring_profile_snapshot_json",
            "score_explanation_json",
            "calculated_risk_level",
            "dimension_template_id",
            "dimension_template_snapshot_json",
            "latest_classification_id",
            "classification_status",
            "classification_summary_json",
            "latest_classification_review_status",
            "open_signal_count",
            "dimension_inputs_json",
            "dimension_score_json",
            "dimension_weighted_score",
            "calculated_dimension_risk_level",
            "residual_likelihood",
            "residual_impact",
            "calculated_residual_risk_level",
            "residual_score_explanation_json",
            "risk_level",
            "likelihood",
            "impact",
            "inherent_risk_score",
            "residual_risk_score",
            "snapshot_sha256",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "archived_records_not_hard_deleted": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
        },
        caveats=(
            "Manual risk records only.",
            "No legal determination or automatic regulatory classification.",
            "Calculated risk level is deterministic presentation output from manual inputs and a configured scoring profile.",
            "Dimension and residual risk outputs are deterministic presentation values from manual inputs and configured templates.",
            "Classification records are manual governance assertions entered by users.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_scoring_profiles",
        title="AI Risk Scoring Profiles",
        description="Manual deterministic scoring profile configuration and assessment score recalculation.",
        route_prefix="/api/v1/ai-governance/ai-risk/scoring-profiles",
        critical_endpoints=(
            "POST /ai-risk/scoring-profiles",
            "POST /ai-risk/scoring-profiles/{profile_id}/preview-score",
            "POST /ai-risk/assessments/{assessment_id}/recalculate-score",
            "GET /ai-risk/scoring-profiles/summary",
        ),
        response_contract_fields=(
            "likelihood_weights_json",
            "impact_weights_json",
            "risk_level_thresholds_json",
            "is_default",
            "calculated_risk_level",
            "inherent_risk_score",
            "score_explanation_json",
            "risk_level",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
        },
        caveats=(
            "Deterministic scoring configuration only.",
            "No legal determination or automatic regulatory classification.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_dimension_templates",
        title="AI Risk Dimension Templates",
        description="Manual deterministic dimension-weighting templates and residual-risk presentation endpoints.",
        route_prefix="/api/v1/ai-governance/ai-risk/dimension-templates",
        critical_endpoints=(
            "POST /ai-risk/dimension-templates",
            "POST /ai-risk/dimension-templates/{template_id}/preview-score",
            "POST /ai-risk/assessments/{assessment_id}/apply-dimension-template",
            "POST /ai-risk/assessments/{assessment_id}/preview-residual-risk",
            "POST /ai-risk/assessments/{assessment_id}/apply-residual-risk",
            "GET /ai-risk/dimension-templates/summary",
        ),
        response_contract_fields=(
            "dimension_weights_json",
            "dimension_thresholds_json",
            "dimension_weighted_score",
            "calculated_dimension_risk_level",
            "residual_risk_score",
            "calculated_residual_risk_level",
            "residual_score_explanation_json",
            "risk_level",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
        },
        caveats=(
            "Deterministic dimension and residual presentation only.",
            "No legal determination or automatic regulatory classification.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_classification_taxonomies",
        title="AI Risk Classification Taxonomies",
        description="Manual taxonomy templates for user-provided classification labels.",
        route_prefix="/api/v1/ai-governance/ai-risk/classification-taxonomies",
        critical_endpoints=(
            "POST /ai-risk/classification-taxonomies",
            "POST /ai-risk/classification-taxonomies/{taxonomy_id}/set-default",
            "POST /ai-risk/classification-taxonomies/{taxonomy_id}/archive",
        ),
        response_contract_fields=(
            "taxonomy_json",
            "methodology_version",
            "is_default",
            "status",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "archived_records_not_hard_deleted": True,
        },
        caveats=(
            "Manual taxonomy templates only.",
            "No legal determination or automatic regulatory classification.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_classification_records",
        title="AI Risk Classification Records",
        description="Manual classification assertions stored against risk assessments.",
        route_prefix="/api/v1/ai-governance/ai-risk",
        critical_endpoints=(
            "POST /ai-risk/assessments/{assessment_id}/classifications",
            "GET /ai-risk/assessments/{assessment_id}/classifications",
            "POST /ai-risk/classifications/{classification_id}/archive",
            "GET /ai-risk/classifications/summary",
        ),
        response_contract_fields=(
            "classification_json",
            "confidence_level",
            "review_status",
            "review_requested_at",
            "reviewed_at",
            "change_request_note",
            "rejection_reason",
            "latest_snapshot_id",
            "open_signal_count",
            "justification",
            "taxonomy_template_snapshot_json",
            "latest_classification_id",
            "classification_status",
            "classification_summary_json",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "archived_records_not_hard_deleted": True,
        },
        caveats=(
            "Manual governance assertions only.",
            "No legal determination or automatic regulatory classification.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_classification_review",
        title="AI Risk Classification Review Controls",
        description="Manual review-state transitions for classification records.",
        route_prefix="/api/v1/ai-governance/ai-risk/classifications",
        critical_endpoints=(
            "POST /ai-risk/classifications/{classification_id}/submit-for-review",
            "POST /ai-risk/classifications/{classification_id}/request-changes",
            "POST /ai-risk/classifications/{classification_id}/mark-reviewed",
            "POST /ai-risk/classifications/{classification_id}/reject",
        ),
        response_contract_fields=(
            "review_status",
            "review_requested_at",
            "reviewed_at",
            "review_note",
            "change_request_note",
            "rejected_at",
            "rejection_reason",
            "open_signal_count",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "archived_records_not_hard_deleted": True,
        },
        caveats=(
            "Reviewed/rejected are internal review states, not legal certification.",
            "No automatic legal or regulatory classification.",
        ),
    ),
    Phase5ContractGroup(
        group_key="ai_risk_classification_snapshots",
        title="AI Risk Classification Snapshots",
        description="Immutable snapshots for classification records.",
        route_prefix="/api/v1/ai-governance/ai-risk/classifications",
        critical_endpoints=(
            "POST /ai-risk/classifications/{classification_id}/snapshots",
            "GET /ai-risk/classifications/{classification_id}/snapshots",
            "GET /ai-risk/classification-snapshots/{snapshot_id}",
        ),
        response_contract_fields=(
            "snapshot_type",
            "snapshot_version",
            "snapshot_json",
            "snapshot_sha256",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "archived_records_not_hard_deleted": True,
            "read_only_endpoint_no_audit": True,
        },
        caveats=("Immutable history snapshots.",),
    ),
    Phase5ContractGroup(
        group_key="governance_signals",
        title="Governance Signals",
        description="Deterministic governance indicators for manual attention.",
        route_prefix="/api/v1/ai-governance/signals",
        critical_endpoints=(
            "GET /signals",
            "GET /signals/{signal_id}",
            "POST /signals/{signal_id}/resolve",
            "POST /signals/{signal_id}/dismiss",
            "POST /ai-risk/assessments/{assessment_id}/refresh-classification-signals",
        ),
        response_contract_fields=(
            "signal_type",
            "reason_code",
            "severity",
            "status",
            "source_json",
            "created_by_system",
            "priority_score",
            "priority_band",
            "priority_explanation_json",
            "group_key",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
        },
        caveats=(
            "Deterministic indicators only.",
            "No approvals/rejections/certifications or automation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_signal_prioritization",
        title="Governance Signal Prioritization",
        description="Deterministic next-best-attention ordering, grouping, and AI-system attention views.",
        route_prefix="/api/v1/ai-governance/signals",
        critical_endpoints=(
            "GET /signals/prioritized",
            "GET /signals/groups",
            "GET /signals/priority-summary",
            "GET /signals/{signal_id}/priority-explanation",
            "GET /ai-systems/{ai_system_id}/attention",
        ),
        response_contract_fields=(
            "priority_score",
            "priority_band",
            "priority_explanation_json",
            "group_key",
            "age_days",
            "highest_priority_score",
            "top_ai_systems_by_attention",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Signal priority is deterministic presentation logic for human attention ordering.",
            "No task creation, recommendation creation, legal determination, or automation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_candidate_actions",
        title="Governance Candidate Actions",
        description="Static deterministic next-best-action candidates derived from open governance signals.",
        route_prefix="/api/v1/ai-governance/actions",
        critical_endpoints=(
            "GET /actions/templates",
            "GET /actions/candidates",
            "GET /actions/candidates/explain",
            "GET /actions/candidate-summary",
            "GET /ai-systems/{ai_system_id}/candidate-actions",
            "GET /ai-risk/assessments/{assessment_id}/candidate-actions",
        ),
        response_contract_fields=(
            "action_key",
            "title",
            "action_type",
            "priority_score",
            "priority_band",
            "source_signal_ids",
            "source_reason_codes",
            "rationale",
            "human_approval_required",
            "automation_allowed",
            "target_entity_type",
            "target_entity_id",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Candidate actions are deterministic suggestions only.",
            "No task/review creation, no legal determination, and no automation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_recommendation_snapshots",
        title="Governance Recommendation Snapshots",
        description="Immutable deterministic candidate-action snapshots with diffable history.",
        route_prefix="/api/v1/ai-governance/recommendations/snapshots",
        critical_endpoints=(
            "POST /recommendations/snapshots/preview",
            "POST /recommendations/snapshots",
            "GET /recommendations/snapshots",
            "GET /recommendations/snapshots/{snapshot_id}",
            "GET /recommendations/snapshots/{snapshot_id}/diff",
            "GET /recommendations/snapshots/latest",
            "GET /recommendations/snapshots/summary",
        ),
        response_contract_fields=(
            "snapshot_id",
            "scope_type",
            "scope_id",
            "candidate_count",
            "recommendation_payload_json",
            "source_signal_ids_json",
            "source_candidate_hash",
            "snapshot_sha256",
            "snapshot_version",
            "previous_snapshot_id",
            "diff_from_previous_json",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Recommendation snapshots preserve deterministic candidate actions at a point in time.",
            "No task/review creation, no automation, and no source record mutation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_recommendation_action_dispositions",
        title="Governance Recommendation Action Dispositions",
        description="Human acknowledgement lifecycle metadata for recommendation actions.",
        route_prefix="/api/v1/ai-governance/recommendations/action-dispositions",
        critical_endpoints=(
            "GET /recommendations/snapshots/{snapshot_id}/actions",
            "POST /recommendations/snapshots/{snapshot_id}/actions/{action_identity_hash}/acknowledge",
            "POST /recommendations/snapshots/{snapshot_id}/actions/{action_identity_hash}/dismiss",
            "POST /recommendations/snapshots/{snapshot_id}/actions/{action_identity_hash}/defer",
            "POST /recommendations/snapshots/{snapshot_id}/actions/{action_identity_hash}/accept-for-manual-work",
            "GET /recommendations/action-dispositions",
            "GET /recommendations/action-dispositions/summary",
        ),
        response_contract_fields=(
            "disposition_id",
            "recommendation_snapshot_id",
            "action_identity_hash",
            "action_key",
            "disposition_status",
            "reason",
            "note",
            "deferred_until",
            "created_by_user_id",
            "updated_by_user_id",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Recommendation action dispositions are human workflow metadata only.",
            "They do not execute recommendations, create tasks/reviews, trigger automation, or mutate source records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_copilot_draft_previews",
        title="Governance Copilot Draft Previews",
        description="Deterministic template-based draft previews from existing governance intelligence context.",
        route_prefix="/api/v1/ai-governance/copilot",
        critical_endpoints=(
            "GET /copilot/draft-types",
            "POST /copilot/drafts/preview",
            "GET /ai-systems/{ai_system_id}/copilot-brief",
            "GET /ai-risk/assessments/{assessment_id}/copilot-brief",
            "GET /recommendations/snapshots/{snapshot_id}/copilot-summary",
            "GET /copilot/executive-risk-summary",
        ),
        response_contract_fields=(
            "draft_type",
            "title",
            "executive_summary",
            "key_findings",
            "recommended_next_steps",
            "open_questions",
            "source_signal_ids",
            "source_recommendation_snapshot_id",
            "source_action_identity_hashes",
            "source_entities_json",
            "generation_mode",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Copilot drafts are deterministic preview content for human review only.",
            "No execution, no task/review creation, no automation, and no legal/regulatory determinations.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_copilot_draft_snapshots",
        title="Governance Copilot Draft Snapshots",
        description="Immutable deterministic copilot draft snapshots with diffable history and source traceability.",
        route_prefix="/api/v1/ai-governance/copilot/draft-snapshots",
        critical_endpoints=(
            "POST /copilot/draft-snapshots/preview",
            "POST /copilot/draft-snapshots",
            "GET /copilot/draft-snapshots",
            "GET /copilot/draft-snapshots/{snapshot_id}",
            "GET /copilot/draft-snapshots/{snapshot_id}/diff",
            "GET /copilot/draft-snapshots/latest",
            "GET /copilot/draft-snapshots/summary",
        ),
        response_contract_fields=(
            "snapshot_id",
            "draft_type",
            "scope_type",
            "scope_id",
            "draft_payload_json",
            "source_entities_json",
            "source_signal_ids_json",
            "source_recommendation_snapshot_id",
            "source_action_identity_hashes_json",
            "source_context_hash",
            "snapshot_sha256",
            "snapshot_version",
            "previous_snapshot_id",
            "diff_from_previous_json",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "manual_first": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
        },
        caveats=(
            "Copilot draft snapshots preserve deterministic draft previews at a point in time.",
            "No task/review creation, no automation, and no source record mutation.",
        ),
    ),
)

PHASE7_CONTRACTS: tuple[Phase5ContractGroup, ...] = (
    Phase5ContractGroup(
        group_key="governance_autopilot_policies",
        title="Governance Autopilot Policies",
        description="Operator-controlled autopilot guardrail policy CRUD and safe default policy resolution.",
        route_prefix="/api/v1/ai-governance/autopilot/policies",
        critical_endpoints=(
            "POST /autopilot/policies",
            "GET /autopilot/policies/resolved",
            "POST /autopilot/policies/{policy_id}/set-default",
            "GET /autopilot/summary",
        ),
        response_contract_fields=(
            "policy_id",
            "status",
            "mode",
            "is_default",
            "allowed_action_types_json",
            "blocked_action_types_json",
            "allowed_draft_types_json",
            "blocked_draft_types_json",
            "approval_required_priority_bands_json",
            "max_allowed_priority_band_for_auto",
            "external_effects_allowed",
            "task_creation_allowed",
            "review_creation_allowed",
            "source_record_mutation_allowed",
            "policy_json",
            "resolved_source",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Phase 7.0 defines deterministic guardrails only.",
            "No execution, no task/review creation, no publishing/approval, and no source record mutation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_policy_evaluations",
        title="Governance Autopilot Policy Evaluations",
        description="Read-only deterministic evaluations of candidate actions, recommendation snapshots, and copilot drafts.",
        route_prefix="/api/v1/ai-governance/autopilot",
        critical_endpoints=(
            "POST /autopilot/evaluate-candidate-action",
            "POST /autopilot/evaluate-recommendation-snapshot",
            "POST /autopilot/evaluate-copilot-draft-snapshot",
        ),
        response_contract_fields=(
            "allowed_by_policy",
            "required_mode",
            "requires_human_approval",
            "blocked_reasons",
            "policy_decision",
            "policy_explanation_json",
            "snapshot_id",
            "total_actions",
            "allowed_count",
            "blocked_count",
            "approval_required_count",
            "decisions",
            "draft_type",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Policy evaluation outputs are guardrail decisions only.",
            "They do not execute automation, create tasks/reviews, approve, publish, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_capabilities",
        title="Governance Autopilot Capabilities",
        description="Deterministic deny-by-default capability matrix used for dry-run execution planning.",
        route_prefix="/api/v1/ai-governance/autopilot/capabilities",
        critical_endpoints=("GET /autopilot/capabilities",),
        response_contract_fields=(
            "capability_key",
            "default_allowed",
            "requires_human_approval",
            "external_effects",
            "creates_task",
            "creates_review",
            "mutates_source_record",
            "allowed_in_phase_7_1",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Capabilities are deny-by-default planning controls.",
            "No execution, no task/review creation, and no source mutation in Phase 7.1.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_execution_intents",
        title="Governance Autopilot Execution Intents",
        description="Dry-run execution planning snapshots from candidate actions/recommendation snapshots/copilot drafts.",
        route_prefix="/api/v1/ai-governance/autopilot/execution-intents",
        critical_endpoints=(
            "POST /autopilot/execution-intents/preview-candidate-action",
            "POST /autopilot/execution-intents/preview-recommendation-snapshot",
            "POST /autopilot/execution-intents/preview-copilot-draft-snapshot",
            "POST /autopilot/execution-intents",
            "GET /autopilot/execution-intents",
            "GET /autopilot/execution-intents/{intent_id}",
            "POST /autopilot/execution-intents/{intent_id}/archive",
            "GET /autopilot/execution-intents/summary",
        ),
        response_contract_fields=(
            "intent_id",
            "source_type",
            "source_id",
            "intent_status",
            "plan_payload_json",
            "capability_decisions_json",
            "approval_required",
            "blocked",
            "blocked_reasons_json",
            "source_hash",
            "intent_sha256",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Execution intents are dry-run planning artifacts.",
            "Phase 7.1 does not execute actions, create tasks/reviews, send notifications, approve/publish, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_approval_policies",
        title="Governance Autopilot Approval Policies",
        description="Organization-scoped dual-control approval policy guardrails with default resolution and fallback.",
        route_prefix="/api/v1/ai-governance/autopilot/approval-policies",
        critical_endpoints=(
            "POST /autopilot/approval-policies",
            "GET /autopilot/approval-policies",
            "GET /autopilot/approval-policies/{policy_id}",
            "PATCH /autopilot/approval-policies/{policy_id}",
            "POST /autopilot/approval-policies/{policy_id}/archive",
            "POST /autopilot/approval-policies/{policy_id}/set-default",
            "GET /autopilot/approval-policies/resolved",
            "GET /autopilot/approval-policies/summary",
        ),
        response_contract_fields=(
            "approval_policy_id",
            "minimum_approvals",
            "rejection_threshold",
            "require_distinct_approvers",
            "block_requester_self_approval",
            "require_quorum_for_priority_bands_json",
            "require_quorum_for_source_types_json",
            "resolved_source",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Approval policy records define dual-control readiness rules only.",
            "Phase 7.3 does not execute actions, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_execution_approvals",
        title="Governance Autopilot Execution Approvals",
        description="Manual approval envelope for execution intents with readiness computation and non-executing authorization metadata.",
        route_prefix="/api/v1/ai-governance/autopilot",
        critical_endpoints=(
            "GET /autopilot/execution-intents/{intent_id}/approval-requirements",
            "POST /autopilot/execution-intents/{intent_id}/approval-requests",
            "GET /autopilot/execution-intents/{intent_id}/approval-requests",
            "POST /autopilot/execution-approvals/{approval_id}/approve",
            "POST /autopilot/execution-approvals/{approval_id}/reject",
            "POST /autopilot/execution-approvals/{approval_id}/cancel",
            "GET /autopilot/execution-intents/{intent_id}/readiness",
            "GET /autopilot/execution-approvals",
            "GET /autopilot/execution-approvals/{approval_id}",
            "GET /autopilot/execution-approvals/summary",
        ),
        response_contract_fields=(
            "approval_id",
            "execution_intent_id",
            "approval_status",
            "requested_by_user_id",
            "requested_at",
            "decided_by_user_id",
            "decided_at",
            "decision_reason",
            "approval_note",
            "approval_policy_snapshot_json",
            "approval_requirements_json",
            "readiness_snapshot_json",
            "approval_vote_count",
            "rejection_vote_count",
            "quorum_met",
            "rejection_threshold_met",
            "readiness_state",
            "ready_for_runner",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Execution approvals record human authorization metadata only.",
            "Phase 7.2 does not execute actions, create tasks/reviews, send notifications, approve compliance, publish, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_approval_votes",
        title="Governance Autopilot Approval Votes",
        description="Dual-control vote capture for execution approvals with distinct approver and requester self-approval boundaries.",
        route_prefix="/api/v1/ai-governance/autopilot/execution-approvals",
        critical_endpoints=(
            "GET /autopilot/execution-approvals/{approval_id}/votes",
            "POST /autopilot/execution-approvals/{approval_id}/votes/approve",
            "POST /autopilot/execution-approvals/{approval_id}/votes/reject",
        ),
        response_contract_fields=(
            "vote_id",
            "approval_id",
            "execution_intent_id",
            "vote_status",
            "voter_user_id",
            "vote_reason",
            "vote_note",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Approval votes are human authorization inputs only.",
            "Phase 7.3 does not execute actions, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_approval_quorum",
        title="Governance Autopilot Approval Quorum",
        description="Read-only quorum and readiness state derived from approval policy, votes, and intent status.",
        route_prefix="/api/v1/ai-governance/autopilot",
        critical_endpoints=(
            "GET /autopilot/execution-approvals/{approval_id}/quorum-status",
            "GET /autopilot/execution-intents/{intent_id}/readiness",
        ),
        response_contract_fields=(
            "approval_id",
            "execution_intent_id",
            "minimum_approvals",
            "approval_vote_count",
            "rejection_vote_count",
            "rejection_threshold",
            "quorum_met",
            "rejection_threshold_met",
            "ready_for_runner",
            "blocked_reasons",
            "resolved_approval_policy",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Quorum state is readiness-only metadata for a future runner.",
            "Phase 7.3 does not execute actions, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_runner_interface",
        title="Governance Autopilot Runner Interface",
        description="Dry-run handoff schema contract and payload verification for a future runner integration.",
        route_prefix="/api/v1/ai-governance/autopilot/runner-interface",
        critical_endpoints=(
            "GET /autopilot/runner-interface/contract",
            "POST /autopilot/runner-interface/verify-handoff",
            "POST /autopilot/execution-intents/{intent_id}/runner-handoff/preview",
        ),
        response_contract_fields=(
            "handoff_schema_version",
            "idempotency_key",
            "operation_key",
            "dry_run",
            "execution_allowed",
            "execution_intent_id",
            "approval_id",
            "readiness_state",
            "ready_for_runner",
            "policy_decision",
            "capability_decisions",
            "proposed_steps",
            "preconditions",
            "blocked_reasons",
            "source_hash",
            "valid",
            "validation_errors",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Runner interface and handoff payloads are dry-run-only in Phase 7.4.",
            "No execution, no queueing, no task/review creation, no external calls, and no source mutation.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_runner_simulations",
        title="Governance Autopilot Runner Simulations",
        description="Persisted non-executing runner simulation records with idempotent create behavior and archive lifecycle.",
        route_prefix="/api/v1/ai-governance/autopilot/runner-simulations",
        critical_endpoints=(
            "POST /autopilot/execution-intents/{intent_id}/runner-simulations",
            "GET /autopilot/runner-simulations",
            "GET /autopilot/runner-simulations/{simulation_id}",
            "POST /autopilot/runner-simulations/{simulation_id}/archive",
            "GET /autopilot/runner-simulations/summary",
        ),
        response_contract_fields=(
            "simulation_id",
            "simulation_status",
            "execution_intent_id",
            "approval_id",
            "handoff_payload_json",
            "readiness_snapshot_json",
            "policy_snapshot_json",
            "capability_snapshot_json",
            "source_hash",
            "idempotency_key",
            "simulation_sha256",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Runner simulations are dry-run planning artifacts for a future runner.",
            "Phase 7.4 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_runner_admissions",
        title="Governance Autopilot Runner Admissions",
        description="Non-executing runner admission records and replay-safe token verification for dry-run handoff control.",
        route_prefix="/api/v1/ai-governance/autopilot/runner-admissions",
        critical_endpoints=(
            "POST /autopilot/runner-simulations/{simulation_id}/admission-preview",
            "POST /autopilot/runner-simulations/{simulation_id}/admissions",
            "GET /autopilot/runner-admissions",
            "GET /autopilot/runner-admissions/{admission_id}",
            "POST /autopilot/runner-admissions/{admission_id}/verify-token",
            "POST /autopilot/runner-admissions/{admission_id}/revoke",
            "POST /autopilot/runner-admissions/{admission_id}/archive",
            "GET /autopilot/runner-admissions/summary",
        ),
        response_contract_fields=(
            "admission_id",
            "runner_simulation_id",
            "execution_intent_id",
            "approval_id",
            "admission_status",
            "readiness_snapshot_json",
            "consistency_checks_json",
            "handoff_payload_json",
            "handoff_token_fingerprint",
            "idempotency_key",
            "token_expires_at",
            "revoked_at",
            "revoke_reason",
            "valid",
            "expired",
            "validation_errors",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Runner admissions and handoff tokens are non-executing guardrail artifacts.",
            "Phase 7.5 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_runner_sessions",
        title="Governance Autopilot Runner Sessions",
        description="Short-lived non-executing runner lease/session envelopes bound to admitted handoff tokens.",
        route_prefix="/api/v1/ai-governance/autopilot",
        critical_endpoints=(
            "POST /autopilot/runner-admissions/{admission_id}/session-preview",
            "POST /autopilot/runner-admissions/{admission_id}/sessions",
            "GET /autopilot/runner-sessions",
            "GET /autopilot/runner-sessions/{session_id}",
            "POST /autopilot/runner-sessions/{session_id}/verify",
            "POST /autopilot/runner-sessions/{session_id}/revoke",
            "POST /autopilot/runner-sessions/{session_id}/archive",
            "POST /autopilot/runner-sessions/expire-stale",
            "GET /autopilot/runner-sessions/summary",
        ),
        response_contract_fields=(
            "session_id",
            "runner_admission_id",
            "runner_simulation_id",
            "execution_intent_id",
            "session_status",
            "admission_token_fingerprint",
            "session_token_fingerprint",
            "lease_payload_json",
            "binding_context_json",
            "attempt_count",
            "max_attempts",
            "replay_window_seconds",
            "expires_at",
            "last_verified_at",
            "revoked_at",
            "revoke_reason",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Runner sessions and leases are non-executing guardrail artifacts.",
            "Phase 7.6 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_autopilot_runner_handshakes",
        title="Governance Autopilot Runner Handshakes",
        description="Non-executing session-to-future-runner handshake envelopes with deterministic idempotency and verification.",
        route_prefix="/api/v1/ai-governance/autopilot",
        critical_endpoints=(
            "GET /autopilot/runner-handshake/contract",
            "POST /autopilot/runner-sessions/{session_id}/handshake-preview",
            "POST /autopilot/runner-sessions/{session_id}/handshakes",
            "GET /autopilot/runner-handshakes",
            "GET /autopilot/runner-handshakes/{handshake_id}",
            "POST /autopilot/runner-handshakes/{handshake_id}/verify",
            "POST /autopilot/runner-handshakes/{handshake_id}/revoke",
            "POST /autopilot/runner-handshakes/{handshake_id}/archive",
            "GET /autopilot/runner-handshakes/summary",
        ),
        response_contract_fields=(
            "handshake_id",
            "runner_session_id",
            "runner_admission_id",
            "runner_simulation_id",
            "execution_intent_id",
            "handshake_status",
            "handshake_payload_json",
            "session_verification_snapshot_json",
            "admission_snapshot_json",
            "simulation_snapshot_json",
            "intent_snapshot_json",
            "idempotency_key",
            "handshake_fingerprint",
            "handshake_sha256",
            "revoked_at",
            "revoke_reason",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "Runner handshakes are non-executing future-runner contract artifacts.",
            "Phase 7.7 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
)

PHASE8_CONTRACTS: tuple[Phase5ContractGroup, ...] = (
    Phase5ContractGroup(
        group_key="governance_noop_runner_events",
        title="Governance No-Op Runner Events",
        description="No-op runner control-plane event records for future-runner eligibility checks without execution.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/contract",
            "POST /autopilot/runner-handshakes/{handshake_id}/noop-runner/preview",
            "POST /autopilot/runner-handshakes/{handshake_id}/noop-runner/events",
            "GET /autopilot/noop-runner/events",
            "GET /autopilot/noop-runner/events/{event_id}",
            "POST /autopilot/noop-runner/events/{event_id}/verify",
            "POST /autopilot/noop-runner/events/{event_id}/archive",
            "GET /autopilot/noop-runner/events/summary",
        ),
        response_contract_fields=(
            "event_id",
            "runner_handshake_id",
            "runner_session_id",
            "runner_admission_id",
            "runner_simulation_id",
            "execution_intent_id",
            "event_status",
            "event_type",
            "noop_only",
            "dry_run",
            "execution_allowed",
            "idempotency_key",
            "event_payload_json",
            "noop_result_json",
            "source_hash",
            "event_sha256",
            "valid",
            "validation_errors",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "persisted_action_audited": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "No-op runner events are non-executing control-plane artifacts only.",
            "Phase 8.0 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_noop_runner_observability",
        title="Governance No-Op Runner Observability",
        description="Read-only operator ledger and control-plane observability reports over no-op runner events.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/ledger",
            "GET /autopilot/noop-runner/reports/timeline",
            "GET /autopilot/noop-runner/reports/blockers",
            "GET /autopilot/noop-runner/reports/readiness",
            "GET /autopilot/noop-runner/reports/idempotency",
            "GET /autopilot/noop-runner/reports/control-plane-health",
        ),
        response_contract_fields=(
            "event_id",
            "event_status",
            "event_type",
            "runner_handshake_id",
            "runner_session_id",
            "runner_admission_id",
            "runner_simulation_id",
            "execution_intent_id",
            "noop_only",
            "dry_run",
            "execution_allowed",
            "idempotency_key",
            "blocked_reasons",
            "source_hash",
            "event_sha256",
            "timeline_buckets",
            "blocker_counts",
            "ready_handshake_count",
            "no_op_logged_count",
            "duplicate_key_attempts_inferred_count",
            "active_duplicate_records_count",
            "real_runner_present",
            "job_queue_present",
            "noop_runner_only",
            "health_status",
            "health_reasons",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
        },
        caveats=(
            "No-op runner observability is read-only control-plane reporting.",
            "Phase 8.2 does not execute actions, queue jobs, create tasks/reviews, send notifications, or mutate governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_noop_runner_operator_diagnostics",
        title="Governance No-Op Runner Operator Diagnostics",
        description="Read-only diagnostics contract and bounded JSON export payloads for no-op runner observability.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner/reports",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/reports/contract",
            "GET /autopilot/noop-runner/reports/diagnostics-manifest",
            "GET /autopilot/noop-runner/reports/compatibility-policy",
            "GET /autopilot/noop-runner/reports/client-contract",
            "GET /autopilot/noop-runner/reports/filter-options",
            "GET /autopilot/noop-runner/reports/pagination-contract",
            "GET /autopilot/noop-runner/reports/field-docs",
            "GET /autopilot/noop-runner/reports/display-metadata",
            "GET /autopilot/noop-runner/reports/localization-map",
            "GET /autopilot/noop-runner/reports/client-hints",
            "GET /autopilot/noop-runner/reports/bounded-export",
            "GET /autopilot/noop-runner/reports/checksum",
        ),
        response_contract_fields=(
            "report_schema_version",
            "compatibility_policy_version",
            "compatibility_policy_endpoint",
            "report_type",
            "generated_at",
            "query_hash",
            "result_hash",
            "limit",
            "offset",
            "truncated",
            "next_offset",
            "row_count",
            "pagination",
            "filter_options_endpoint",
            "pagination_contract_endpoint",
            "client_contract_endpoint",
            "field_docs_endpoint",
            "display_metadata_endpoint",
            "localization_map_endpoint",
            "client_hints_endpoint",
            "safety_flags",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
            "json_api_only_no_files": True,
        },
        caveats=(
            "Operator diagnostics and bounded export payloads are read-only JSON responses.",
            "Phase 8.5 does not execute actions, queue jobs, create tasks/reviews, create files, call external services, send notifications, publish, approve compliance, or mutate source governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_noop_runner_diagnostics_compatibility",
        title="Governance No-Op Runner Diagnostics Compatibility",
        description="Read-only compatibility policy guarantees for no-op runner diagnostics and bounded export response shapes.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner/reports",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/reports/compatibility-policy",
        ),
        response_contract_fields=(
            "report_schema_version",
            "compatibility_policy_version",
            "additive_fields_allowed",
            "breaking_changes_require_new_schema_version",
            "deprecated_fields_policy",
            "minimum_supported_schema_version",
            "current_supported_schema_version",
            "stable_endpoint_families",
            "safety_flags",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
            "json_api_only_no_files": True,
        },
        caveats=(
            "Diagnostics compatibility guarantees are read-only API-contract metadata.",
            "Phase 8.5 does not execute actions, queue jobs, create tasks, create reviews, create files, call external services, send notifications, publish, approve compliance, or mutate source governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_noop_runner_client_integration",
        title="Governance No-Op Runner Client Integration",
        description="Read-only client-integration metadata for stable filters, enums, and pagination contracts over no-op runner diagnostics.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner/reports",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/reports/client-contract",
            "GET /autopilot/noop-runner/reports/filter-options",
            "GET /autopilot/noop-runner/reports/pagination-contract",
            "GET /autopilot/noop-runner/reports/field-docs",
            "GET /autopilot/noop-runner/reports/display-metadata",
            "GET /autopilot/noop-runner/reports/client-hints",
        ),
        response_contract_fields=(
            "client_contract_version",
            "supported_filters_by_endpoint",
            "pagination_contract",
            "enum_values",
            "default_limits",
            "max_limits",
            "filter_options",
            "field_docs_endpoint",
            "display_metadata_endpoint",
            "localization_map_endpoint",
            "client_hints_endpoint",
            "safety_flags",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
            "json_api_only_no_files": True,
        },
        caveats=(
            "Client integration metadata is read-only API-contract metadata.",
            "Phase 8.5 does not execute actions, queue jobs, create tasks, create reviews, create files, call external services, send notifications, publish, approve compliance, or mutate source governance records.",
        ),
    ),
    Phase5ContractGroup(
        group_key="governance_noop_runner_client_field_docs",
        title="Governance No-Op Runner Client Field Docs",
        description="Read-only field-level docs, display metadata, localization keys, and client hints for no-op runner diagnostics.",
        route_prefix="/api/v1/ai-governance/autopilot/noop-runner/reports",
        critical_endpoints=(
            "GET /contracts/phase8",
            "GET /autopilot/noop-runner/reports/field-docs",
            "GET /autopilot/noop-runner/reports/display-metadata",
            "GET /autopilot/noop-runner/reports/localization-map",
            "GET /autopilot/noop-runner/reports/client-hints",
        ),
        response_contract_fields=(
            "field_docs_version",
            "display_metadata_version",
            "localization_map_version",
            "client_hints_version",
            "field_docs",
            "table_columns",
            "default_sort",
            "status_badges",
            "localization_keys",
            "safety_flags",
            "caveat",
        ),
        invariants={
            "tenant_scoped": True,
            "read_only_endpoint_no_audit": True,
            "deterministic_only": True,
            "manual_first": True,
            "json_api_only_no_files": True,
        },
        caveats=(
            "Field-level client docs and display metadata are read-only API metadata.",
            "Phase 8.5 does not execute actions, queue jobs, create tasks, create reviews, create files, call external services, send notifications, publish, approve compliance, or mutate source governance records.",
        ),
    ),
)


class AIGovernanceContractService:
    PHASE = "phase5"
    STATUS = "closed"
    CAVEAT = (
        "Phase 5 contract records are internal API stability contracts. "
        "They do not create, update, approve, reject, classify, or automate governance workflows."
    )
    PHASE6 = "phase6"
    PHASE6_STATUS = "foundation"
    PHASE6_CAVEAT = (
        "Phase 6 contract records are internal API stability contracts for manual-first risk governance surfaces. "
        "They do not make legal determinations or automatically classify regulatory status."
    )
    PHASE7 = "phase7"
    PHASE7_STATUS = "foundation"
    PHASE7_CAVEAT = (
        "Autopilot policies define deterministic guardrails and evaluation decisions. "
        "No real runner exists in Phase 7. "
        "Phase 7 does not execute automation, create tasks, create reviews, approve, publish, "
        "or mutate governance records. "
        "Phase 7 does not make legal or regulatory determinations."
    )
    PHASE8 = "phase8"
    PHASE8_STATUS = "foundation"
    PHASE8_CAVEAT = (
        "Phase 8 introduces no-op runner control-plane logging, read-only observability, bounded JSON diagnostics, compatibility metadata, client-integration contract polish, and field-level display metadata only. "
        "No real runner exists and execution remains disabled. "
        "Phase 8 does not execute automation, queue jobs, create tasks, create reviews, "
        "or mutate governance records. "
        "Phase 8 does not create file exports or external storage artifacts. "
        "Phase 8 does not make legal or regulatory determinations."
    )

    def list_phase5_contracts(self) -> list[dict]:
        return [group.as_dict() for group in PHASE5_CONTRACTS]

    def get_phase5_contract(self, group_key: str) -> dict | None:
        for group in PHASE5_CONTRACTS:
            if group.group_key == group_key:
                return group.as_dict()
        return None

    def phase5_contracts_response(self) -> dict:
        groups = self.list_phase5_contracts()
        return {
            "phase": self.PHASE,
            "status": self.STATUS,
            "group_count": len(groups),
            "groups": groups,
            "caveat": self.CAVEAT,
        }

    def phase5_compatibility_summary(self) -> dict:
        groups = self.list_phase5_contracts()
        protected_endpoint_count = sum(len(group["critical_endpoints"]) for group in groups)
        return {
            "phase": self.PHASE,
            "status": self.STATUS,
            "protected_groups_count": len(groups),
            "protected_endpoint_count": protected_endpoint_count,
            "contract_testing_strategy": (
                "Key-presence and representative type checks on critical Phase 5 endpoints; "
                "read-only contract endpoints with no persistence/audit side effects."
            ),
            "caveat": self.CAVEAT,
        }

    def list_phase6_contracts(self) -> list[dict]:
        return [group.as_dict() for group in PHASE6_CONTRACTS]

    def get_phase6_contract(self, group_key: str) -> dict | None:
        for group in PHASE6_CONTRACTS:
            if group.group_key == group_key:
                return group.as_dict()
        return None

    def phase6_contracts_response(self) -> dict:
        groups = self.list_phase6_contracts()
        return {
            "phase": self.PHASE6,
            "status": self.PHASE6_STATUS,
            "group_count": len(groups),
            "groups": groups,
            "caveat": self.PHASE6_CAVEAT,
        }

    def list_phase7_contracts(self) -> list[dict]:
        return [group.as_dict() for group in PHASE7_CONTRACTS]

    def get_phase7_contract(self, group_key: str) -> dict | None:
        for group in PHASE7_CONTRACTS:
            if group.group_key == group_key:
                return group.as_dict()
        return None

    def phase7_contracts_response(self) -> dict:
        groups = self.list_phase7_contracts()
        return {
            "phase": self.PHASE7,
            "status": self.PHASE7_STATUS,
            "group_count": len(groups),
            "groups": groups,
            "execution_allowed": False,
            "real_runner_present": False,
            "job_queue_present": False,
            "future_runner_requires_architecture_review": True,
            "caveat": self.PHASE7_CAVEAT,
        }

    def list_phase8_contracts(self) -> list[dict]:
        return [group.as_dict() for group in PHASE8_CONTRACTS]

    def get_phase8_contract(self, group_key: str) -> dict | None:
        for group in PHASE8_CONTRACTS:
            if group.group_key == group_key:
                return group.as_dict()
        return None

    def phase8_contracts_response(self) -> dict:
        groups = self.list_phase8_contracts()
        return {
            "phase": self.PHASE8,
            "status": self.PHASE8_STATUS,
            "group_count": len(groups),
            "groups": groups,
            "execution_allowed": False,
            "real_runner_present": False,
            "job_queue_present": False,
            "noop_runner_only": True,
            "caveat": self.PHASE8_CAVEAT,
        }
