class ComplianceContractService:
    COMMON_INVARIANTS = ["tenant_scoped", "soft_delete", "audit_logged"]

    def registry(self) -> dict:
        return {
            "contract_groups": {
                "compliance_policies": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/policies"},
                        {"method": "GET", "path": "/api/v1/compliance/policies"},
                        {"method": "GET", "path": "/api/v1/compliance/policies/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/policies/{policy_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/policies/{policy_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/policies/{policy_id}/archive"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "approved_by_user_id",
                        "approved_at",
                        "archived_at",
                        "archived_by_user_id",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "compliance_policy_versions": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/policies/{policy_id}/versions"},
                        {"method": "GET", "path": "/api/v1/compliance/policies/{policy_id}/versions"},
                        {"method": "GET", "path": "/api/v1/compliance/policies/{policy_id}/versions/{version_id}"},
                        {
                            "method": "POST",
                            "path": "/api/v1/compliance/policies/{policy_id}/versions/{version_id}/submit-for-approval",
                        },
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "policy_id",
                        "content_sha256",
                        "submitted_by_user_id",
                        "submitted_at",
                        "reviewed_by_user_id",
                        "reviewed_at",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "compliance_policy_control_links": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/policies/{policy_id}/links/controls"},
                        {"method": "GET", "path": "/api/v1/compliance/policies/{policy_id}/links/controls"},
                        {
                            "method": "POST",
                            "path": "/api/v1/compliance/policies/{policy_id}/links/controls/{link_id}/unlink",
                        },
                        {"method": "GET", "path": "/api/v1/compliance/policies/{policy_id}/links/summary"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "policy_id", "linked_by_user_id", "created_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "vendors": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/vendors"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/vendors/{vendor_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/vendors/{vendor_id}/archive"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "archived_at",
                        "archived_by_user_id",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "vendor_assessments": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/{assessment_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/{assessment_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/{assessment_id}/start"},
                        {
                            "method": "POST",
                            "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/{assessment_id}/complete",
                        },
                        {
                            "method": "POST",
                            "path": "/api/v1/compliance/vendors/{vendor_id}/assessments/{assessment_id}/cancel",
                        },
                    ],
                    "protected_response_fields": ["id", "organization_id", "vendor_id", "created_by_user_id", "created_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "vendor_risk_scores": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/vendors/{vendor_id}/risk-scores"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/risk-scores"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/risk-scores/latest"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/risk-scores/{score_id}"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "vendor_id",
                        "assessment_id",
                        "inherent_risk_score",
                        "score_explanation_json",
                        "created_at",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "vendor_control_links": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/vendors/{vendor_id}/links/controls"},
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/links/controls"},
                        {
                            "method": "POST",
                            "path": "/api/v1/compliance/vendors/{vendor_id}/links/controls/{link_id}/unlink",
                        },
                        {"method": "GET", "path": "/api/v1/compliance/vendors/{vendor_id}/links/summary"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "vendor_id", "linked_by_user_id", "created_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "control_monitoring_definitions": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/definitions"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/definitions"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/definitions/{def_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/monitoring/definitions/{def_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/definitions/{def_id}/archive"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/definitions/{def_id}/activate"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/definitions/{def_id}/deactivate"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/definitions/{def_id}/record-result"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/definitions/{def_id}/results"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/results"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/summary"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "control_id", "created_at", "updated_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "control_monitoring_rules": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/rules"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/rules"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/rules/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/rules/{rule_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/monitoring/rules/{rule_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/rules/{rule_id}/archive"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/rules/{rule_id}/activate"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/rules/{rule_id}/deactivate"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/rules/evaluate"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/rules/executions"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/rules/executions/{exec_id}"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "created_by_user_id", "created_at", "updated_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "control_monitoring_alerts": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/alerts"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/alerts"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/alerts/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/monitoring/alerts/{alert_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/alerts/{alert_id}/acknowledge"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/alerts/{alert_id}/resolve"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/alerts/{alert_id}/dismiss"},
                        {"method": "POST", "path": "/api/v1/compliance/monitoring/alerts/{alert_id}/assign"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "created_at", "updated_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "compliance_deadlines": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/deadlines"},
                        {"method": "GET", "path": "/api/v1/compliance/deadlines"},
                        {"method": "GET", "path": "/api/v1/compliance/deadlines/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/deadlines/events"},
                        {"method": "POST", "path": "/api/v1/compliance/deadlines/evaluate-due"},
                        {"method": "GET", "path": "/api/v1/compliance/deadlines/{deadline_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/deadlines/{deadline_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/deadlines/{deadline_id}/complete"},
                        {"method": "POST", "path": "/api/v1/compliance/deadlines/{deadline_id}/waive"},
                        {"method": "POST", "path": "/api/v1/compliance/deadlines/{deadline_id}/cancel"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "created_by_user_id",
                        "created_at",
                        "updated_at",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "risk_indicators": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/risk-indicators"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-indicators"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-indicators/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-indicators/{indicator_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/risk-indicators/{indicator_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/risk-indicators/{indicator_id}/recalculate"},
                        {"method": "POST", "path": "/api/v1/compliance/risk-indicators/{indicator_id}/archive"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "current_value",
                        "status",
                        "last_calculated_at",
                        "archived_at",
                        "archived_by_user_id",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "risk_appetite": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/risk-appetite"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-appetite"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-appetite/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-appetite/breaches"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-appetite/{threshold_id}"},
                        {"method": "PATCH", "path": "/api/v1/compliance/risk-appetite/{threshold_id}"},
                        {"method": "POST", "path": "/api/v1/compliance/risk-appetite/{threshold_id}/deactivate"},
                    ],
                    "protected_response_fields": ["id", "organization_id", "created_by_user_id", "created_at", "updated_at"],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "entity_risk_scores": {
                    "endpoints": [
                        {"method": "POST", "path": "/api/v1/compliance/risk-scores/compute-entity"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-scores/summary"},
                        {"method": "GET", "path": "/api/v1/compliance/risk-scores/by-entity"},
                    ],
                    "protected_response_fields": [
                        "id",
                        "organization_id",
                        "entity_type",
                        "entity_id",
                        "composite_score",
                        "score_band",
                        "computed_at",
                    ],
                    "invariants": self.COMMON_INVARIANTS,
                },
                "compliance_dashboard": {
                    "endpoints": [
                        {"method": "GET", "path": "/api/v1/compliance/dashboard/posture-summary"},
                        {"method": "GET", "path": "/api/v1/compliance/dashboard/framework-readiness"},
                        {"method": "GET", "path": "/api/v1/compliance/dashboard/control-health"},
                        {"method": "GET", "path": "/api/v1/compliance/dashboard/risk-heatmap"},
                        {"method": "GET", "path": "/api/v1/compliance/dashboard/recent-activity"},
                    ],
                    "protected_response_fields": ["read_only"],
                    "invariants": ["tenant_scoped", "read_only", "no_audit_write"],
                },
            }
        }
