from __future__ import annotations

NIST_800_53_SECTIONS: list[dict[str, int | str]] = [
    {"code": "AC", "title": "Access Control", "order": 1},
    {"code": "AT", "title": "Awareness and Training", "order": 2},
    {"code": "AU", "title": "Audit and Accountability", "order": 3},
    {"code": "CA", "title": "Assessment, Authorization, Monitoring", "order": 4},
    {"code": "CM", "title": "Configuration Management", "order": 5},
    {"code": "CP", "title": "Contingency Planning", "order": 6},
    {"code": "IA", "title": "Identification and Authentication", "order": 7},
    {"code": "IR", "title": "Incident Response", "order": 8},
    {"code": "MA", "title": "Maintenance", "order": 9},
    {"code": "MP", "title": "Media Protection", "order": 10},
    {"code": "PE", "title": "Physical and Environmental Protection", "order": 11},
    {"code": "PL", "title": "Planning", "order": 12},
    {"code": "PM", "title": "Program Management", "order": 13},
    {"code": "PS", "title": "Personnel Security", "order": 14},
    {"code": "PT", "title": "Personally Identifiable Information Processing", "order": 15},
    {"code": "RA", "title": "Risk Assessment", "order": 16},
    {"code": "SA", "title": "System and Services Acquisition", "order": 17},
    {"code": "SC", "title": "System and Communications Protection", "order": 18},
    {"code": "SI", "title": "System and Information Integrity", "order": 19},
    {"code": "SR", "title": "Supply Chain Risk Management", "order": 20},
]

# (reference_code, title, family)
NIST_800_53_LOW_CONTROLS_RAW: list[tuple[str, str, str]] = [
    ("AC-1", "Access Control Policy and Procedures", "AC"),
    ("AC-2", "Account Management", "AC"),
    ("AC-3", "Access Enforcement", "AC"),
    ("AC-7", "Unsuccessful Logon Attempts", "AC"),
    ("AC-8", "System Use Notification", "AC"),
    ("AC-11", "Device Lock", "AC"),
    ("AC-12", "Session Termination", "AC"),
    ("AC-14", "Permitted Actions Without Identification", "AC"),
    ("AC-17", "Remote Access", "AC"),
    ("AC-18", "Wireless Access", "AC"),
    ("AC-19", "Access Control for Mobile Devices", "AC"),
    ("AC-20", "Use of External Systems", "AC"),
    ("AC-22", "Publicly Accessible Content", "AC"),
    ("AT-1", "Awareness and Training Policy and Procedures", "AT"),
    ("AT-2", "Literacy Training and Awareness", "AT"),
    ("AT-3", "Role-Based Training", "AT"),
    ("AT-4", "Training Records", "AT"),
    ("AU-1", "Audit and Accountability Policy", "AU"),
    ("AU-2", "Event Logging", "AU"),
    ("AU-3", "Content of Audit Records", "AU"),
    ("AU-4", "Audit Log Storage Capacity", "AU"),
    ("AU-5", "Response to Audit Processing Failures", "AU"),
    ("AU-6", "Audit Record Review, Analysis, Reporting", "AU"),
    ("AU-7", "Audit Record Reduction and Report Generation", "AU"),
    ("AU-8", "Time Stamps", "AU"),
    ("AU-9", "Protection of Audit Information", "AU"),
    ("AU-11", "Audit Record Retention", "AU"),
    ("AU-12", "Audit Record Generation", "AU"),
    ("CA-1", "Assessment, Authorization Policy", "CA"),
    ("CA-2", "Control Assessments", "CA"),
    ("CA-3", "Information Exchange", "CA"),
    ("CA-5", "Plan of Action and Milestones", "CA"),
    ("CA-6", "Authorization", "CA"),
    ("CA-7", "Continuous Monitoring", "CA"),
    ("CA-9", "Internal System Connections", "CA"),
    ("CM-1", "Configuration Management Policy", "CM"),
    ("CM-2", "Baseline Configuration", "CM"),
    ("CM-4", "Impact Analyses", "CM"),
    ("CM-5", "Access Restrictions for Change", "CM"),
    ("CM-6", "Configuration Settings", "CM"),
    ("CM-7", "Least Functionality", "CM"),
    ("CM-8", "System Component Inventory", "CM"),
    ("CM-10", "Software Usage Restrictions", "CM"),
    ("CM-11", "User-Installed Software", "CM"),
    ("CP-1", "Contingency Planning Policy", "CP"),
    ("CP-2", "Contingency Plan", "CP"),
    ("CP-3", "Contingency Training", "CP"),
    ("CP-4", "Contingency Plan Testing", "CP"),
    ("CP-6", "Alternate Storage Site", "CP"),
    ("CP-7", "Alternate Processing Site", "CP"),
    ("CP-8", "Telecommunications Services", "CP"),
    ("CP-9", "System Backup", "CP"),
    ("CP-10", "System Recovery and Reconstitution", "CP"),
    ("IA-1", "Identification and Authentication Policy", "IA"),
    ("IA-2", "Identification and Authentication (Org Users)", "IA"),
    ("IA-3", "Device Identification and Authentication", "IA"),
    ("IA-4", "Identifier Management", "IA"),
    ("IA-5", "Authenticator Management", "IA"),
    ("IA-6", "Authentication Feedback", "IA"),
    ("IA-7", "Cryptographic Module Authentication", "IA"),
    ("IA-8", "Identification and Authentication (Non-Org Users)", "IA"),
    ("IA-11", "Re-Authentication", "IA"),
    ("IR-1", "Incident Response Policy", "IR"),
    ("IR-2", "Incident Response Training", "IR"),
    ("IR-3", "Incident Response Testing", "IR"),
    ("IR-4", "Incident Handling", "IR"),
    ("IR-5", "Incident Monitoring", "IR"),
    ("IR-6", "Incident Reporting", "IR"),
    ("IR-7", "Incident Response Assistance", "IR"),
    ("IR-8", "Incident Response Plan", "IR"),
    ("IR-9", "Information Spillage Response", "IR"),
    ("MA-1", "Maintenance Policy", "MA"),
    ("MA-2", "Controlled Maintenance", "MA"),
    ("MA-4", "Nonlocal Maintenance", "MA"),
    ("MA-5", "Maintenance Personnel", "MA"),
    ("MP-1", "Media Protection Policy", "MP"),
    ("MP-2", "Media Access", "MP"),
    ("MP-6", "Media Sanitization", "MP"),
    ("MP-7", "Media Use", "MP"),
    ("PE-1", "Physical and Environmental Policy", "PE"),
    ("PE-2", "Physical Access Authorizations", "PE"),
    ("PE-3", "Physical Access Control", "PE"),
    ("PE-6", "Monitoring Physical Access", "PE"),
    ("PE-8", "Visitor Access Records", "PE"),
    ("PE-12", "Emergency Lighting", "PE"),
    ("PE-13", "Fire Protection", "PE"),
    ("PE-14", "Environmental Controls", "PE"),
    ("PE-15", "Water Damage Protection", "PE"),
    ("PE-16", "Delivery and Removal", "PE"),
    ("PL-1", "Planning Policy", "PL"),
    ("PL-2", "System Security and Privacy Plans", "PL"),
    ("PL-4", "Rules of Behavior", "PL"),
    ("PL-10", "Baseline Selection", "PL"),
    ("PL-11", "Baseline Tailoring", "PL"),
    ("PM-1", "Information Security Program Plan", "PM"),
    ("PM-2", "Information Security Program Leadership", "PM"),
    ("PM-3", "Information Security and Privacy Resources", "PM"),
    ("PM-4", "Plan of Action and Milestones Process", "PM"),
    ("PM-5", "System Inventory", "PM"),
    ("PM-6", "Measures of Performance", "PM"),
    ("PM-7", "Enterprise Architecture", "PM"),
    ("PM-9", "Risk Management Strategy", "PM"),
    ("PM-10", "Authorization Process", "PM"),
    ("PM-11", "Mission and Business Process Definition", "PM"),
    ("PM-13", "Security and Privacy Workforce", "PM"),
    ("PM-14", "Testing, Training, and Monitoring", "PM"),
    ("PM-15", "Security and Privacy Groups and Associations", "PM"),
    ("PM-16", "Threat Awareness Program", "PM"),
    ("PS-1", "Personnel Security Policy", "PS"),
    ("PS-2", "Position Risk Designation", "PS"),
    ("PS-3", "Personnel Screening", "PS"),
    ("PS-4", "Personnel Termination", "PS"),
    ("PS-5", "Personnel Transfer", "PS"),
    ("PS-6", "Access Agreements", "PS"),
    ("PS-7", "External Personnel Security", "PS"),
    ("PS-8", "Personnel Sanctions", "PS"),
    ("PT-1", "Personally Identifiable Information Policy", "PT"),
    ("PT-2", "Authority to Process Personally Identifiable Information", "PT"),
    ("PT-3", "Personally Identifiable Information Processing Purposes", "PT"),
    ("PT-4", "Consent", "PT"),
    ("PT-5", "Privacy Notice", "PT"),
    ("PT-6", "System of Records Notice", "PT"),
    ("PT-7", "Specific Categories of Personally Identifiable Information", "PT"),
    ("RA-1", "Risk Assessment Policy", "RA"),
    ("RA-2", "Security Categorization", "RA"),
    ("RA-3", "Risk Assessment", "RA"),
    ("RA-5", "Vulnerability Monitoring and Scanning", "RA"),
    ("RA-7", "Risk Response", "RA"),
    ("RA-9", "Criticality Analysis", "RA"),
    ("SA-1", "System and Services Acquisition Policy", "SA"),
    ("SA-2", "Allocation of Resources", "SA"),
    ("SA-3", "System Development Life Cycle", "SA"),
    ("SA-4", "Acquisition Process", "SA"),
    ("SA-5", "System Documentation", "SA"),
    ("SA-8", "Security and Privacy Engineering Principles", "SA"),
    ("SA-9", "External System Services", "SA"),
    ("SA-10", "Developer Configuration Management", "SA"),
    ("SA-11", "Developer Testing and Evaluation", "SA"),
    ("SC-1", "System and Communications Protection Policy", "SC"),
    ("SC-5", "Denial-of-Service Protection", "SC"),
    ("SC-7", "Boundary Protection", "SC"),
    ("SC-8", "Transmission Confidentiality and Integrity", "SC"),
    ("SC-12", "Cryptographic Key Establishment and Management", "SC"),
    ("SC-13", "Cryptographic Protection", "SC"),
    ("SC-15", "Collaborative Computing Devices", "SC"),
    ("SC-17", "Public Key Infrastructure Certificates", "SC"),
    ("SC-18", "Mobile Code", "SC"),
    ("SC-20", "Secure Name/Address Resolution Service", "SC"),
    ("SC-21", "Secure Name/Address Resolution (Recursive or Caching Resolver)", "SC"),
    ("SC-22", "Architecture and Provisioning for Name/Address Resolution Service", "SC"),
    ("SC-28", "Protection of Information at Rest", "SC"),
    ("SC-39", "Process Isolation", "SC"),
    ("SI-1", "System and Information Integrity Policy", "SI"),
    ("SI-2", "Flaw Remediation", "SI"),
    ("SI-3", "Malicious Code Protection", "SI"),
    ("SI-4", "System Monitoring", "SI"),
    ("SI-5", "Security Alerts, Advisories, Notices", "SI"),
    ("SI-7", "Software, Firmware, Information Integrity", "SI"),
    ("SI-8", "Spam Protection", "SI"),
    ("SI-10", "Information Input Validation", "SI"),
    ("SI-11", "Error Handling", "SI"),
    ("SI-12", "Information Management and Retention", "SI"),
    ("SI-16", "Memory Protection", "SI"),
    ("SR-1", "Supply Chain Risk Management Policy", "SR"),
    ("SR-2", "Supply Chain Risk Management Plan", "SR"),
    ("SR-3", "Supply Chain Controls and Processes", "SR"),
    ("SR-5", "Acquisition Strategies, Tools, Methods", "SR"),
    ("SR-6", "Supplier Assessments and Reviews", "SR"),
    ("SR-8", "Notification Agreements", "SR"),
    ("SR-10", "Inspection of Systems and Components", "SR"),
    ("SR-11", "Component Authenticity", "SR"),
]

_NIST_TARGET_LOW_COUNT = 125
_NIST_MANDATORY_REFS = {"AC-3", "AT-2", "AU-6", "IR-4", "RA-3", "SC-8"}
_seen_nist_refs: set[str] = set()
NIST_800_53_LOW_CONTROLS: list[tuple[str, str, str]] = []
for _ref, _title, _family in NIST_800_53_LOW_CONTROLS_RAW:
    if _ref in _seen_nist_refs:
        continue
    _seen_nist_refs.add(_ref)
    NIST_800_53_LOW_CONTROLS.append((_ref, _title, _family))
if len(NIST_800_53_LOW_CONTROLS) > _NIST_TARGET_LOW_COUNT:
    NIST_800_53_LOW_CONTROLS = NIST_800_53_LOW_CONTROLS[:_NIST_TARGET_LOW_COUNT]
_present_refs = {ref for ref, _, _ in NIST_800_53_LOW_CONTROLS}
if _NIST_MANDATORY_REFS - _present_refs:
    _raw_by_ref = {ref: (ref, title, family) for ref, title, family in NIST_800_53_LOW_CONTROLS_RAW}
    _replace_idx = len(NIST_800_53_LOW_CONTROLS) - 1
    for _ref in sorted(_NIST_MANDATORY_REFS):
        if _ref in _present_refs or _ref not in _raw_by_ref:
            continue
        while _replace_idx >= 0 and NIST_800_53_LOW_CONTROLS[_replace_idx][0] in _NIST_MANDATORY_REFS:
            _replace_idx -= 1
        if _replace_idx < 0:
            break
        NIST_800_53_LOW_CONTROLS[_replace_idx] = _raw_by_ref[_ref]
        _present_refs.add(_ref)
        _replace_idx -= 1

NIST_800_53_QUESTIONS: list[dict[str, int | str | list[str]]] = [
    {
        "question_key": "federal_system",
        "question_text": "Is this system operated by or on behalf of a US federal agency?",
        "help_text": "",
        "triggers_scope": "all",
        "order_index": 1,
        "answer_type": "boolean",
    },
    {
        "question_key": "impact_level",
        "question_text": "What is the system's FIPS 199 impact categorization?",
        "help_text": (
            "LOW impact: 125 controls. "
            "MODERATE impact: 325 controls (v2 expansion). "
            "HIGH impact: 421 controls (v3 expansion)."
        ),
        "triggers_scope": "partial",
        "order_index": 2,
        "answer_type": "single_select",
        "choices": ["LOW", "MODERATE", "HIGH"],
    },
]

NIST_FAMILY_EVIDENCE_HINTS: dict[str, list[str]] = {
    "AC": ["access_control_policy", "access_review_records", "account_provisioning_log"],
    "AT": ["security_training_curriculum", "training_completion_records", "role_based_training_matrix"],
    "AU": ["audit_logging_standard", "siem_log_exports", "audit_review_records"],
    "CA": ["control_assessment_report", "poam_register", "authorization_package"],
    "CM": ["configuration_baseline", "change_control_records", "asset_inventory"],
    "CP": ["contingency_plan", "backup_test_results", "recovery_exercise_report"],
    "IA": ["identity_management_policy", "authenticator_configuration", "access_authentication_logs"],
    "IR": ["incident_response_plan", "incident_ticket_records", "tabletop_exercise_results"],
    "MA": ["maintenance_policy", "maintenance_logs", "maintenance_personnel_authorizations"],
    "MP": ["media_protection_policy", "media_access_log", "media_sanitization_records"],
    "PE": ["physical_security_policy", "badge_access_logs", "visitor_log"],
    "PL": ["system_security_plan", "rules_of_behavior_acknowledgements", "baseline_selection_record"],
    "PM": ["security_program_plan", "program_metrics_dashboard", "workforce_program_records"],
    "PS": ["personnel_security_policy", "screening_records", "termination_checklist"],
    "PT": ["privacy_policy", "consent_records", "pii_processing_inventory"],
    "RA": ["risk_assessment_report", "vulnerability_scan_results", "risk_response_plan"],
    "SA": ["secure_sdlc_policy", "supplier_security_requirements", "developer_test_evidence"],
    "SC": ["network_security_architecture", "encryption_standard", "boundary_protection_logs"],
    "SI": ["vulnerability_management_process", "malware_protection_reports", "integrity_monitoring_logs"],
    "SR": ["supply_chain_risk_plan", "supplier_assessment_reports", "component_authenticity_checks"],
}

FAMILY_DESCRIPTIONS: dict[str, str] = {
    "AC": "requires policies and technical safeguards to restrict and enforce logical access based on authorized need.",
    "AT": "requires workforce awareness and role-based security training with retained evidence of completion.",
    "AU": "requires generation, protection, retention, and review of audit records to support accountability and investigations.",
    "CA": "requires periodic security assessments, authorization decisions, and continuous monitoring of controls and interconnections.",
    "CM": "requires controlled baselines, secure configuration settings, and governed changes to system components.",
    "CP": "requires contingency preparation, backup, alternate processing capabilities, and tested recovery procedures.",
    "IA": "requires strong identity proofing, account identifiers, and authenticator controls for users and devices.",
    "IR": "requires documented incident handling capabilities including detection, response, reporting, and after-action improvement.",
    "MA": "requires controlled system maintenance activities and oversight of maintenance personnel and methods.",
    "MP": "requires safeguarding system media through controlled access, handling, transport, and sanitization.",
    "PE": "requires physical protections for facilities, entry controls, monitoring, and environmental safeguards.",
    "PL": "requires planning artifacts including security plans, rules of behavior, and baseline selection/tailoring decisions.",
    "PM": "requires organization-level governance, strategy, resources, and oversight for the security and privacy program.",
    "PS": "requires personnel lifecycle controls such as screening, agreements, transfer, termination, and sanctions.",
    "PT": "requires privacy governance for lawful processing, notices, consent, and handling of PII categories.",
    "RA": "requires categorization of systems, risk analyses, and risk-informed response decisions.",
    "SA": "requires acquisition and development practices that integrate security and privacy requirements across suppliers and SDLC.",
    "SC": "requires boundary, transmission, cryptographic, and architectural protections for system communications.",
    "SI": "requires flaw remediation, malicious code defenses, monitoring, and integrity protections for information and systems.",
    "SR": "requires supply chain risk governance, supplier controls, and assurance over component authenticity and quality.",
}


def nist_description(reference_code: str, title: str, family: str) -> str:
    family_text = FAMILY_DESCRIPTIONS.get(family, "requires documented controls and evidence to meet the control objective.")
    return f"{reference_code} ({title}) {family_text}"


def nist_evidence_hints(family: str) -> list[str]:
    return list(NIST_FAMILY_EVIDENCE_HINTS.get(family, ["policy_document", "procedure_document", "operational_evidence"]))


HIPAA_SECTIONS: list[dict[str, int | str]] = [
    {"code": "HIPAA-PR", "title": "Privacy Rule", "order": 1},
    {"code": "HIPAA-SR", "title": "Security Rule", "order": 2},
    {"code": "HIPAA-BNR", "title": "Breach Notification Rule", "order": 3},
]

# (reference_code, title, description, section_code, evidence_hints)
HIPAA_OBLIGATIONS: list[tuple[str, str, str, str, list[str]]] = [
    (
        "HIPAA-164.502",
        "Uses and Disclosures of PHI",
        "Covered entities may only use or disclose PHI as permitted by the Privacy Rule or with patient authorization.",
        "HIPAA-PR",
        ["privacy_policy", "authorization_forms", "disclosure_log"],
    ),
    (
        "HIPAA-164.504",
        "Uses and Disclosures — Org Requirements",
        "Covered entities must have written contracts with business associates and document their uses and disclosures of PHI.",
        "HIPAA-PR",
        ["baa_contracts", "business_associate_list"],
    ),
    (
        "HIPAA-164.514",
        "Other Requirements for PHI",
        "Covered entities must follow the minimum necessary standard and de-identify PHI when appropriate.",
        "HIPAA-PR",
        ["data_minimization_policy", "deidentification_procedure"],
    ),
    (
        "HIPAA-164.520",
        "Notice of Privacy Practices",
        "Covered entities must provide individuals with a clear notice describing PHI uses and HIPAA rights.",
        "HIPAA-PR",
        ["notice_of_privacy_practices", "patient_acknowledgement_records"],
    ),
    (
        "HIPAA-164.522",
        "Rights to Request Privacy Protection",
        "Individuals may request restrictions and confidential communications for their PHI.",
        "HIPAA-PR",
        ["restriction_request_process", "confidential_communication_requests"],
    ),
    (
        "HIPAA-164.524",
        "Access of Individuals to PHI",
        "Individuals have a right to inspect or obtain copies of PHI generally within 30 days.",
        "HIPAA-PR",
        ["patient_access_procedure", "request_response_records"],
    ),
    (
        "HIPAA-164.526",
        "Amendment of PHI",
        "Individuals can request corrections to PHI and covered entities must process requests per rule timelines.",
        "HIPAA-PR",
        ["amendment_request_log", "amendment_decision_records"],
    ),
    (
        "HIPAA-164.528",
        "Accounting of Disclosures",
        "Covered entities must provide an accounting of certain PHI disclosures upon request.",
        "HIPAA-PR",
        ["disclosure_accounting_log", "disclosure_tracking_procedure"],
    ),
    (
        "HIPAA-164.308-a1",
        "Security Management Process",
        "Organizations must implement policies and procedures to prevent, detect, contain, and correct security violations.",
        "HIPAA-SR",
        ["security_risk_analysis", "risk_management_plan", "sanction_policy"],
    ),
    (
        "HIPAA-164.308-a2",
        "Assigned Security Responsibility",
        "A designated security official must be responsible for developing and implementing HIPAA security policies.",
        "HIPAA-SR",
        ["hipaa_security_officer_designation", "role_description"],
    ),
    (
        "HIPAA-164.308-a3",
        "Workforce Security",
        "Policies must ensure workforce access to PHI is authorized, supervised, and terminated appropriately.",
        "HIPAA-SR",
        ["access_authorization_policy", "workforce_clearance_procedure", "termination_procedure"],
    ),
    (
        "HIPAA-164.308-a4",
        "Information Access Management",
        "Access to PHI must be limited to authorized users and aligned with role-based requirements.",
        "HIPAA-SR",
        ["access_control_policy", "access_review_records"],
    ),
    (
        "HIPAA-164.308-a5",
        "Security Awareness and Training",
        "A security awareness and training program must be implemented for the workforce.",
        "HIPAA-SR",
        ["training_records", "training_curriculum", "phishing_test_results"],
    ),
    (
        "HIPAA-164.308-a6",
        "Security Incident Procedures",
        "Covered entities must identify and respond to suspected or known security incidents.",
        "HIPAA-SR",
        ["incident_response_plan", "incident_response_records"],
    ),
    (
        "HIPAA-164.308-a7",
        "Contingency Plan",
        "Emergency mode operation, backup, and disaster recovery procedures are required for systems containing PHI.",
        "HIPAA-SR",
        ["contingency_plan", "backup_test_results", "disaster_recovery_plan"],
    ),
    (
        "HIPAA-164.308-a8",
        "Evaluation",
        "Periodic technical and non-technical evaluations must assess safeguards against HIPAA requirements.",
        "HIPAA-SR",
        ["security_evaluation_report", "penetration_test_report"],
    ),
    (
        "HIPAA-164.310-a1",
        "Physical Access Controls",
        "Organizations must implement facility access controls that protect systems containing electronic PHI.",
        "HIPAA-SR",
        ["physical_access_policy", "facility_access_records", "visitor_log"],
    ),
    (
        "HIPAA-164.310-b",
        "Workstation Use",
        "Workstation use policies must define appropriate functions and physical safeguards.",
        "HIPAA-SR",
        ["workstation_policy", "workstation_configuration_records"],
    ),
    (
        "HIPAA-164.310-d1",
        "Device and Media Controls",
        "Policies must govern receipt, removal, movement, and disposal of media that contains electronic PHI.",
        "HIPAA-SR",
        ["media_disposal_policy", "device_inventory", "media_sanitization_records"],
    ),
    (
        "HIPAA-164.312-a1",
        "Access Control (Technical)",
        "Technical controls must enforce access to electronic PHI only for authorized persons or software.",
        "HIPAA-SR",
        ["access_control_configuration", "unique_user_id_evidence", "automatic_logoff_config"],
    ),
    (
        "HIPAA-164.312-b",
        "Audit Controls",
        "Mechanisms must record and examine activity in systems that contain or use electronic PHI.",
        "HIPAA-SR",
        ["audit_log_configuration", "audit_log_review_records"],
    ),
    (
        "HIPAA-164.312-c1",
        "Integrity Controls",
        "Entities must protect electronic PHI from improper alteration or destruction.",
        "HIPAA-SR",
        ["integrity_policy", "data_validation_evidence"],
    ),
    (
        "HIPAA-164.312-d",
        "Authentication",
        "Procedures must verify that a person or entity seeking access is who they claim to be.",
        "HIPAA-SR",
        ["mfa_implementation_evidence", "authentication_policy"],
    ),
    (
        "HIPAA-164.312-e1",
        "Transmission Security",
        "Technical measures must protect electronic PHI against unauthorized access during transmission.",
        "HIPAA-SR",
        ["tls_configuration", "vpn_evidence", "encryption_policy"],
    ),
    (
        "HIPAA-164.400",
        "Notification to Individuals",
        "Following a breach of unsecured PHI, affected individuals must be notified without unreasonable delay and no later than 60 days.",
        "HIPAA-BNR",
        ["breach_notification_letters", "mailing_records", "timeline_documentation"],
    ),
    (
        "HIPAA-164.404",
        "Notification to Media",
        "For breaches affecting more than 500 residents of a state or jurisdiction, prominent media outlets must be notified within 60 days.",
        "HIPAA-BNR",
        ["media_notification_records", "breach_scope_assessment"],
    ),
    (
        "HIPAA-164.406",
        "Notification to HHS",
        "Breaches over 500 individuals must be reported to HHS within 60 days; smaller breaches may be reported annually.",
        "HIPAA-BNR",
        ["hhs_notification_record", "breach_assessment_documentation"],
    ),
    (
        "HIPAA-164.410",
        "Notification by Business Associates",
        "Business associates must notify covered entities of PHI breaches without unreasonable delay and no later than 60 days.",
        "HIPAA-BNR",
        ["ba_breach_notification", "baa_breach_clause_evidence"],
    ),
]

HIPAA_QUESTIONS: list[dict[str, int | str]] = [
    {
        "question_key": "covered_entity_or_ba",
        "question_text": "Is your organization a HIPAA covered entity or business associate?",
        "help_text": (
            "Covered entities: health plans, healthcare clearinghouses, and healthcare providers who transmit PHI electronically. "
            "Business associates: organizations that create, receive, maintain, or transmit PHI on behalf of a covered entity."
        ),
        "triggers_scope": "all",
        "order_index": 1,
        "answer_type": "boolean",
    },
    {
        "question_key": "handles_phi",
        "question_text": "Does your organization process, store, or transmit Protected Health Information (PHI)?",
        "help_text": "",
        "triggers_scope": "all",
        "order_index": 2,
        "answer_type": "boolean",
    },
]

HIPAA_NIST_MAPPINGS: list[tuple[str, str, str]] = [
    ("HIPAA-164.308-a1", "RA-3", "equivalent"),
    ("HIPAA-164.308-a5", "AT-2", "equivalent"),
    ("HIPAA-164.308-a6", "IR-4", "equivalent"),
    ("HIPAA-164.312-a1", "AC-3", "equivalent"),
    ("HIPAA-164.312-b", "AU-6", "equivalent"),
    ("HIPAA-164.312-e1", "SC-8", "equivalent"),
]
