from __future__ import annotations

CIS_CONTROLS_V8_SECTIONS: list[dict[str, int | str]] = [
    {"code": "CIS-01", "title": "Inventory and Control of Enterprise Assets", "order": 1},
    {"code": "CIS-02", "title": "Inventory and Control of Software Assets", "order": 2},
    {"code": "CIS-03", "title": "Data Protection", "order": 3},
    {"code": "CIS-04", "title": "Secure Configuration of Enterprise Assets", "order": 4},
    {"code": "CIS-05", "title": "Account Management", "order": 5},
    {"code": "CIS-06", "title": "Access Control Management", "order": 6},
    {"code": "CIS-07", "title": "Continuous Vulnerability Management", "order": 7},
    {"code": "CIS-08", "title": "Audit Log Management", "order": 8},
    {"code": "CIS-09", "title": "Email and Web Browser Protections", "order": 9},
    {"code": "CIS-10", "title": "Malware Defenses", "order": 10},
    {"code": "CIS-11", "title": "Data Recovery", "order": 11},
    {"code": "CIS-12", "title": "Network Infrastructure Management", "order": 12},
    {"code": "CIS-13", "title": "Network Monitoring and Defense", "order": 13},
    {"code": "CIS-14", "title": "Security Awareness and Skills Training", "order": 14},
    {"code": "CIS-15", "title": "Service Provider Management", "order": 15},
    {"code": "CIS-16", "title": "Application Software Security", "order": 16},
    {"code": "CIS-17", "title": "Incident Response Management", "order": 17},
    {"code": "CIS-18", "title": "Penetration Testing", "order": 18},
]

# (reference_code, title, section_code, ig_level)
CIS_CONTROLS_V8_SAFEGUARDS: list[tuple[str, str, str, str]] = [
    ("CIS-1.1", "Establish and Maintain Detailed Enterprise Asset Inventory", "CIS-01", "IG1"),
    ("CIS-1.2", "Address Unauthorized Assets", "CIS-01", "IG1"),
    ("CIS-1.3", "Utilize an Active Discovery Tool", "CIS-01", "IG2"),
    ("CIS-1.4", "Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory", "CIS-01", "IG2"),
    ("CIS-1.5", "Use a Passive Asset Discovery Tool", "CIS-01", "IG2"),
    ("CIS-2.1", "Establish and Maintain a Software Inventory", "CIS-02", "IG1"),
    ("CIS-2.2", "Ensure Authorized Software is Currently Supported", "CIS-02", "IG1"),
    ("CIS-2.3", "Address Unauthorized Software", "CIS-02", "IG2"),
    ("CIS-2.4", "Utilize Automated Software Inventory Tools", "CIS-02", "IG2"),
    ("CIS-2.5", "Allowlist Authorized Software", "CIS-02", "IG2"),
    ("CIS-2.6", "Allowlist Authorized Libraries", "CIS-02", "IG2"),
    ("CIS-2.7", "Allowlist Authorized Scripts", "CIS-02", "IG2"),
    ("CIS-3.1", "Establish and Maintain a Data Management Process", "CIS-03", "IG1"),
    ("CIS-3.2", "Establish and Maintain a Data Inventory", "CIS-03", "IG1"),
    ("CIS-3.3", "Configure Data Access Control Lists", "CIS-03", "IG2"),
    ("CIS-3.4", "Enforce Data Retention", "CIS-03", "IG2"),
    ("CIS-3.5", "Securely Dispose of Data", "CIS-03", "IG2"),
    ("CIS-3.6", "Encrypt Data on End-User Devices", "CIS-03", "IG2"),
    ("CIS-3.7", "Establish and Maintain a Data Classification Scheme", "CIS-03", "IG1"),
    ("CIS-3.8", "Document Data Flows", "CIS-03", "IG2"),
    ("CIS-3.9", "Encrypt Data on Removable Media", "CIS-03", "IG3"),
    ("CIS-3.10", "Encrypt Sensitive Data in Transit", "CIS-03", "IG2"),
    ("CIS-3.11", "Encrypt Sensitive Data at Rest", "CIS-03", "IG2"),
    ("CIS-3.12", "Segment Data Processing and Storage Based on Sensitivity", "CIS-03", "IG2"),
    ("CIS-3.13", "Deploy a Data Loss Prevention Solution", "CIS-03", "IG3"),
    ("CIS-3.14", "Log Sensitive Data Access", "CIS-03", "IG3"),
    ("CIS-4.1", "Establish and Maintain a Secure Configuration Process", "CIS-04", "IG1"),
    ("CIS-4.2", "Establish and Maintain a Secure Configuration Process for Network Infrastructure", "CIS-04", "IG1"),
    ("CIS-4.3", "Configure Automatic Session Locking on Enterprise Assets", "CIS-04", "IG2"),
    ("CIS-4.4", "Implement and Manage a Firewall on Servers", "CIS-04", "IG2"),
    ("CIS-4.5", "Implement and Manage a Firewall on End-User Devices", "CIS-04", "IG1"),
    ("CIS-4.6", "Securely Manage Enterprise Assets and Software", "CIS-04", "IG2"),
    ("CIS-4.7", "Manage Default Accounts on Enterprise Assets and Software", "CIS-04", "IG2"),
    ("CIS-4.8", "Uninstall or Disable Unnecessary Services on Enterprise Assets and Software", "CIS-04", "IG3"),
    ("CIS-4.9", "Configure Trusted DNS Servers on Enterprise Assets", "CIS-04", "IG2"),
    ("CIS-4.10", "Enforce Automatic Device Lockout on Portable End-User Devices", "CIS-04", "IG3"),
    ("CIS-4.11", "Enforce Remote Wipe Capability on Portable End-User Devices", "CIS-04", "IG3"),
    ("CIS-4.12", "Separate Enterprise Workspaces on Mobile End-User Devices", "CIS-04", "IG2"),
    ("CIS-5.1", "Establish and Maintain an Inventory of Accounts", "CIS-05", "IG1"),
    ("CIS-5.2", "Use Unique Passwords", "CIS-05", "IG1"),
    ("CIS-5.3", "Disable Dormant Accounts", "CIS-05", "IG2"),
    ("CIS-5.4", "Restrict Administrator Privileges to Dedicated Administrator Accounts", "CIS-05", "IG1"),
    ("CIS-5.5", "Establish and Maintain an Inventory of Service Accounts", "CIS-05", "IG2"),
    ("CIS-5.6", "Centralize Account Management", "CIS-05", "IG3"),
    ("CIS-6.1", "Establish an Access Granting Process", "CIS-06", "IG1"),
    ("CIS-6.2", "Establish an Access Revoking Process", "CIS-06", "IG1"),
    ("CIS-6.3", "Require MFA for Externally-Exposed Applications", "CIS-06", "IG2"),
    ("CIS-6.4", "Require MFA for Remote Network Access", "CIS-06", "IG2"),
    ("CIS-6.5", "Require MFA for Administrative Access", "CIS-06", "IG3"),
    ("CIS-6.6", "Establish and Maintain an Inventory of Authentication and Authorization Systems", "CIS-06", "IG2"),
    ("CIS-6.7", "Centralize Access Control", "CIS-06", "IG2"),
    ("CIS-6.8", "Define and Maintain Role-Based Access Control", "CIS-06", "IG3"),
    ("CIS-7.1", "Establish and Maintain a Vulnerability Management Process", "CIS-07", "IG1"),
    ("CIS-7.2", "Establish and Maintain a Remediation Process", "CIS-07", "IG1"),
    ("CIS-7.3", "Perform Automated Operating System Patch Management", "CIS-07", "IG2"),
    ("CIS-7.4", "Perform Automated Application Patch Management", "CIS-07", "IG2"),
    ("CIS-7.5", "Perform Automated Vulnerability Scans of Internal Enterprise Assets", "CIS-07", "IG2"),
    ("CIS-7.6", "Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets", "CIS-07", "IG2"),
    ("CIS-7.7", "Remediate Detected Vulnerabilities", "CIS-07", "IG3"),
    ("CIS-8.1", "Establish and Maintain an Audit Log Management Process", "CIS-08", "IG1"),
    ("CIS-8.2", "Collect Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.3", "Ensure Adequate Audit Log Storage", "CIS-08", "IG2"),
    ("CIS-8.4", "Standardize Time Synchronization", "CIS-08", "IG2"),
    ("CIS-8.5", "Collect Detailed Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.6", "Collect DNS Query Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.7", "Collect URL Request Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.8", "Collect Command-Line Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.9", "Centralize Audit Logs", "CIS-08", "IG3"),
    ("CIS-8.10", "Retain Audit Logs", "CIS-08", "IG2"),
    ("CIS-8.11", "Conduct Audit Log Reviews", "CIS-08", "IG3"),
    ("CIS-8.12", "Collect Service Provider Logs", "CIS-08", "IG3"),
    ("CIS-9.1", "Ensure Use of Only Fully Supported Browsers and Email Clients", "CIS-09", "IG1"),
    ("CIS-9.2", "Use DNS Filtering Services", "CIS-09", "IG2"),
    ("CIS-9.3", "Maintain and Enforce Network-Based URL Filters", "CIS-09", "IG2"),
    ("CIS-9.4", "Restrict Unnecessary or Unauthorized Browser and Email Client Extensions", "CIS-09", "IG2"),
    ("CIS-9.5", "Implement DMARC", "CIS-09", "IG2"),
    ("CIS-9.6", "Block Unnecessary File Types", "CIS-09", "IG2"),
    ("CIS-9.7", "Deploy and Maintain Email Server Anti-Malware Protections", "CIS-09", "IG2"),
    ("CIS-10.1", "Deploy and Maintain Anti-Malware Software", "CIS-10", "IG1"),
    ("CIS-10.2", "Configure Automatic Anti-Malware Signature Updates", "CIS-10", "IG2"),
    ("CIS-10.3", "Disable Autorun and Autoplay for Removable Media", "CIS-10", "IG1"),
    ("CIS-10.4", "Configure Automatic Anti-Malware Scanning of Removable Media", "CIS-10", "IG2"),
    ("CIS-10.5", "Enable Anti-Exploitation Features", "CIS-10", "IG2"),
    ("CIS-10.6", "Centrally Manage Anti-Malware Software", "CIS-10", "IG3"),
    ("CIS-10.7", "Use Behavior-Based Anti-Malware Software", "CIS-10", "IG3"),
    ("CIS-11.1", "Establish and Maintain a Data Recovery Process", "CIS-11", "IG1"),
    ("CIS-11.2", "Perform Automated Backups", "CIS-11", "IG1"),
    ("CIS-11.3", "Protect Recovery Data", "CIS-11", "IG1"),
    ("CIS-11.4", "Establish and Maintain an Isolated Instance of Recovery Data", "CIS-11", "IG2"),
    ("CIS-11.5", "Test Data Recovery", "CIS-11", "IG2"),
    ("CIS-12.1", "Ensure Network Infrastructure is Up-to-Date", "CIS-12", "IG2"),
    ("CIS-12.2", "Establish and Maintain a Secure Network Architecture", "CIS-12", "IG2"),
    ("CIS-12.3", "Securely Manage Network Infrastructure", "CIS-12", "IG2"),
    ("CIS-12.4", "Establish and Maintain Architecture Diagram(s)", "CIS-12", "IG2"),
    ("CIS-12.5", "Centralize Network Authentication, Authorization, and Auditing (AAA)", "CIS-12", "IG2"),
    ("CIS-12.6", "Use of Secure Network Management and Communication Protocols", "CIS-12", "IG3"),
    ("CIS-12.7", "Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise's AAA Infrastructure", "CIS-12", "IG3"),
    ("CIS-12.8", "Establish and Maintain Dedicated Computing Resources for All Administrative Work", "CIS-12", "IG3"),
    ("CIS-13.1", "Centralize Security Event Alerting", "CIS-13", "IG2"),
    ("CIS-13.2", "Deploy a Host-Based Intrusion Detection Solution", "CIS-13", "IG2"),
    ("CIS-13.3", "Deploy a Network Intrusion Detection Solution", "CIS-13", "IG3"),
    ("CIS-13.4", "Perform Traffic Filtering Between Network Segments", "CIS-13", "IG3"),
    ("CIS-13.5", "Manage Access Control for Remote Assets", "CIS-13", "IG2"),
    ("CIS-13.6", "Collect Network Traffic Flow Logs", "CIS-13", "IG2"),
    ("CIS-13.7", "Deploy a Host-Based Intrusion Prevention Solution", "CIS-13", "IG3"),
    ("CIS-13.8", "Deploy a Network Intrusion Prevention Solution", "CIS-13", "IG3"),
    ("CIS-13.9", "Deploy Port-Level Access Control", "CIS-13", "IG3"),
    ("CIS-13.10", "Perform Application Layer Filtering", "CIS-13", "IG3"),
    ("CIS-13.11", "Tune Security Event Alerting Thresholds", "CIS-13", "IG3"),
    ("CIS-14.1", "Establish and Maintain a Security Awareness Program", "CIS-14", "IG1"),
    ("CIS-14.2", "Train Workforce Members to Recognize Social Engineering Attacks", "CIS-14", "IG1"),
    ("CIS-14.3", "Train Workforce Members on Authentication Best Practices", "CIS-14", "IG2"),
    ("CIS-14.4", "Train Workforce on Data Handling Best Practices", "CIS-14", "IG2"),
    ("CIS-14.5", "Train Workforce Members on Causes of Unintentional Data Exposure", "CIS-14", "IG2"),
    ("CIS-14.6", "Train Workforce Members on Recognizing and Reporting Security Incidents", "CIS-14", "IG2"),
    ("CIS-14.7", "Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates", "CIS-14", "IG2"),
    ("CIS-14.8", "Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks", "CIS-14", "IG3"),
    ("CIS-14.9", "Conduct Role-Specific Security Awareness and Skills Training", "CIS-14", "IG3"),
    ("CIS-15.1", "Establish and Maintain an Inventory of Service Providers", "CIS-15", "IG1"),
    ("CIS-15.2", "Establish and Maintain a Service Provider Management Policy", "CIS-15", "IG2"),
    ("CIS-15.3", "Classify Service Providers", "CIS-15", "IG2"),
    ("CIS-15.4", "Ensure Service Provider Contracts Include Security Requirements", "CIS-15", "IG2"),
    ("CIS-15.5", "Assess Service Providers", "CIS-15", "IG3"),
    ("CIS-15.6", "Monitor Service Providers", "CIS-15", "IG3"),
    ("CIS-15.7", "Securely Decommission Service Providers", "CIS-15", "IG3"),
    ("CIS-16.1", "Establish and Maintain a Secure Application Development Process", "CIS-16", "IG2"),
    ("CIS-16.2", "Establish and Maintain a Process to Accept and Address Software Vulnerabilities", "CIS-16", "IG2"),
    ("CIS-16.3", "Perform Root Cause Analysis on Security Vulnerabilities", "CIS-16", "IG2"),
    ("CIS-16.4", "Establish and Maintain an Application Security Testing Process", "CIS-16", "IG2"),
    ("CIS-16.5", "Use Up-to-Date and Trusted Third-Party Software Components", "CIS-16", "IG2"),
    ("CIS-16.6", "Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities", "CIS-16", "IG2"),
    ("CIS-16.7", "Use Standard Hardening Configuration Templates for Application Infrastructure", "CIS-16", "IG2"),
    ("CIS-16.8", "Separate Production and Non-Production Systems", "CIS-16", "IG3"),
    ("CIS-16.9", "Train Developers in Application Security Concepts and Secure Coding", "CIS-16", "IG3"),
    ("CIS-16.10", "Apply Secure Design Principles in Application Architectures", "CIS-16", "IG3"),
    ("CIS-16.11", "Leverage Vetted Modules or Services for Application Security Components", "CIS-16", "IG3"),
    ("CIS-16.12", "Implement Code-Level Security Checks", "CIS-16", "IG3"),
    ("CIS-16.13", "Conduct Application Penetration Testing", "CIS-16", "IG3"),
    ("CIS-16.14", "Conduct Threat Modeling", "CIS-16", "IG3"),
    ("CIS-17.1", "Designate Personnel to Manage Incident Handling", "CIS-17", "IG1"),
    ("CIS-17.2", "Establish and Maintain Contact Information for Reporting Security Incidents", "CIS-17", "IG2"),
    ("CIS-17.3", "Establish and Maintain an Enterprise Process for Reporting Incidents", "CIS-17", "IG2"),
    ("CIS-17.4", "Establish and Maintain an Incident Response Process", "CIS-17", "IG1"),
    ("CIS-17.5", "Assign Key Roles and Responsibilities for Incident Response", "CIS-17", "IG2"),
    ("CIS-17.6", "Define Mechanisms for Communicating During Incident Response", "CIS-17", "IG3"),
    ("CIS-17.7", "Conduct Routine Incident Response Exercises", "CIS-17", "IG3"),
    ("CIS-17.8", "Conduct Post-Incident Reviews", "CIS-17", "IG3"),
    ("CIS-17.9", "Establish and Maintain Security Incident Thresholds", "CIS-17", "IG3"),
    ("CIS-18.1", "Establish and Maintain a Penetration Testing Program", "CIS-18", "IG2"),
    ("CIS-18.2", "Perform Periodic External Penetration Tests", "CIS-18", "IG2"),
    ("CIS-18.3", "Remediate Penetration Test Findings", "CIS-18", "IG3"),
    ("CIS-18.4", "Validate Security Measures", "CIS-18", "IG3"),
    ("CIS-18.5", "Perform Periodic Internal Penetration Tests", "CIS-18", "IG3"),
]

CIS_CONTROLS_V8_QUESTIONS: list[dict[str, int | str | list[str]]] = [
    {
        "question_key": "implementation_group",
        "question_text": "What is your organization's cybersecurity maturity and resource level?",
        "triggers_scope": "partial",
        "order_index": 1,
        "help_text": (
            "IG1 (56 safeguards): Small organizations with limited IT security resources. Basic hygiene. "
            "IG2 (130 safeguards): Mid-size organizations with dedicated security staff. "
            "IG3 (153 safeguards): Large organizations with security specialists. Full controls."
        ),
        "answer_type": "single_select",
        "choices": ["IG1", "IG2", "IG3"],
    }
]

ISO_27701_SECTIONS: list[dict[str, int | str]] = [
    {"code": "CTRL", "title": "PII Controller Requirements", "order": 1},
    {"code": "PROC", "title": "PII Processor Requirements", "order": 2},
    {"code": "ISO27002-EXT", "title": "ISO 27002 Extension Controls", "order": 3},
]

# (reference_code, title, section_code)
ISO_27701_OBLIGATIONS: list[tuple[str, str, str]] = [
    ("27701-7.2.1", "Identify and document purpose", "CTRL"),
    ("27701-7.2.2", "Identify lawful basis", "CTRL"),
    ("27701-7.2.3", "Determine when and how consent is obtained", "CTRL"),
    ("27701-7.2.5", "Privacy notice", "CTRL"),
    ("27701-7.2.6", "Provide mechanism to object or withdraw consent", "CTRL"),
    ("27701-7.2.7", "Automated individual decision-making", "CTRL"),
    ("27701-7.3.1", "Rights of PII principals — access", "CTRL"),
    ("27701-7.3.2", "Correction and deletion", "CTRL"),
    ("27701-7.3.3", "Rights related to automated processing", "CTRL"),
    ("27701-7.3.4", "Data portability", "CTRL"),
    ("27701-7.4.1", "Privacy by design and by default", "CTRL"),
    ("27701-7.4.2", "Privacy risk assessment", "CTRL"),
    ("27701-7.4.3", "Records of PII processing activities", "CTRL"),
    ("27701-7.5.1", "Agreements with PII processors", "CTRL"),
    ("27701-7.5.2", "Transfers of PII", "CTRL"),
    ("27701-8.2.1", "Customer agreement", "PROC"),
    ("27701-8.2.2", "Organization's purposes", "PROC"),
    ("27701-8.2.3", "Marketing and advertising", "PROC"),
    ("27701-8.2.4", "Infringement of applicable legislation", "PROC"),
    ("27701-8.3.1", "Notification of sub-processors", "PROC"),
    ("27701-8.4.1", "Obligations to PII principals", "PROC"),
    ("27701-8.4.2", "Erasure", "PROC"),
    ("27701-8.5.1", "Contract terms", "PROC"),
    ("27701-8.5.2", "Sub-processor contracts", "PROC"),
    ("27701-8.5.5", "Records of PII processed", "PROC"),
]

ISO_27701_QUESTIONS: list[dict[str, int | str | list[str]]] = [
    {
        "question_key": "pii_role",
        "question_text": "What is your organization's role in relation to personal data?",
        "triggers_scope": "partial",
        "order_index": 1,
        "help_text": (
            "Controller: You determine the purpose and means of processing. Clauses 7.x apply. "
            "Processor: You process data on behalf of a controller. Clauses 8.x apply. "
            "Both: All clauses apply."
        ),
        "answer_type": "single_select",
        "choices": ["controller", "processor", "both"],
    },
    {
        "question_key": "has_iso_27001",
        "question_text": "Does your organization have or is implementing ISO 27001?",
        "triggers_scope": "all",
        "order_index": 2,
        "help_text": "ISO 27701 extends ISO 27001. It can be implemented as an extension to an existing ISMS or standalone.",
        "answer_type": "boolean",
    },
]

# (iso_27701_reference_code, gdpr_reference_code, mapping_type)
ISO_27701_GDPR_MAPPINGS: list[tuple[str, str, str]] = [
    ("27701-7.2.2", "GDPR-OBL-02", "equivalent"),
    ("27701-7.3.1", "GDPR-OBL-04", "equivalent"),
    ("27701-7.3.2", "GDPR-OBL-05", "equivalent"),
    ("27701-7.3.4", "GDPR-OBL-04", "equivalent"),
    ("27701-7.4.1", "GDPR-OBL-10", "equivalent"),
    ("27701-7.4.3", "GDPR-OBL-07", "equivalent"),
    ("27701-7.5.1", "GDPR-OBL-09", "equivalent"),
    ("27701-7.2.5", "GDPR-OBL-03", "equivalent"),
]
