from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.control import Control
from app.models.audit_engagement import AuditEngagement
from app.models.ai_governance_diagnostic_snapshot import AIGovernanceDiagnosticSnapshot
from app.models.board_scorecard_snapshot import BoardScorecardSnapshot
from app.models.control_obligation_mapping import ControlObligationMapping
from app.models.evidence_control_link import EvidenceControlLink
from app.models.evidence_item import EvidenceItem
from app.models.framework import Framework
from app.models.obligation import Obligation
from app.models.organization import Organization
from app.models.organization_framework import OrganizationFramework
from app.models.organization_obligation_state import OrganizationObligationState
from app.models.organization_export_setting import OrganizationExportSetting
from app.models.risk import Risk
from app.models.user import User
from app.repositories.control_repository import ControlRepository
from app.repositories.risk_repository import RiskRepository
from app.services.compliance_dashboard_service import ComplianceDashboardService
from app.services.compliance_policy_service import CompliancePolicyService
from app.services.vendor_service import VendorService


@dataclass
class ExportBranding:
    organization_id: uuid.UUID
    company_display_name: str
    logo_url: str | None = None
    footer_text: str = "Generated by CompliVibe"
    primary_color_hex: str = "#1F4B99"


@dataclass
class ExportSection:
    title: str
    rows: list[tuple[str, str]] = field(default_factory=list)
    paragraphs: list[str] = field(default_factory=list)
    items: list[str] = field(default_factory=list)


@dataclass
class ExportDocumentContent:
    organization_id: uuid.UUID
    title: str
    subtitle: str | None
    generated_at: datetime
    entity_type: str
    entity_id: uuid.UUID | None
    report_type: str | None
    branding: ExportBranding
    sections: list[ExportSection]


class ExportContentBuilder:
    def __init__(self, db: Session):
        self.db = db

    @staticmethod
    def _now() -> datetime:
        return datetime.now(UTC)

    def _org_or_404(self, org_id: uuid.UUID) -> Organization:
        org = self.db.get(Organization, org_id)
        if org is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Organization not found")
        return org

    def _branding(self, org_id: uuid.UUID) -> ExportBranding:
        org = self._org_or_404(org_id)
        row = (
            self.db.query(OrganizationExportSetting)
            .filter(OrganizationExportSetting.organization_id == org_id)
            .first()
        )
        if row is None:
            return ExportBranding(
                organization_id=org_id,
                company_display_name=org.name,
            )
        return ExportBranding(
            organization_id=org_id,
            company_display_name=row.company_display_name or org.name,
            logo_url=row.logo_url,
            footer_text=row.footer_text or "Generated by CompliVibe",
            primary_color_hex=row.primary_color_hex or "#1F4B99",
        )

    def _owner_insight(self, owner_user_id: uuid.UUID | None) -> str | None:
        """Flag when an entity's owner has been deactivated elsewhere in the platform.

        Exports are frequently pulled well after the fact (audits, board packets); a
        deactivated owner means nobody is actively accountable for the item and that
        needs to be visible on the document itself, not just inferred by a reader who
        happens to also check the user directory.
        """
        if owner_user_id is None:
            return "No owner assigned - accountability gap."
        owner = self.db.get(User, owner_user_id)
        if owner is None:
            return "Assigned owner no longer exists in this organization."
        if not owner.is_active or owner.status != "active":
            return f"Assigned owner ({owner.email}) is deactivated - reassign before relying on this record."
        return None

    @staticmethod
    def _to_rows(payload: dict[str, Any], prefix: str = "") -> list[tuple[str, str]]:
        rows: list[tuple[str, str]] = []
        for key, value in payload.items():
            label = f"{prefix}{key}".replace("_", " ").title()
            if isinstance(value, dict):
                rows.extend(ExportContentBuilder._to_rows(value, prefix=f"{label} / "))
            elif isinstance(value, list):
                rows.append((label, ", ".join(str(item) for item in value)))
            else:
                rows.append((label, "" if value is None else str(value)))
        return rows

    def build_policy(self, org_id: uuid.UUID, policy_id: uuid.UUID) -> ExportDocumentContent:
        policy = CompliancePolicyService(self.db).require_policy_in_org(org_id, policy_id)
        sections = [
            ExportSection(
                title="Policy",
                rows=[
                    ("Title", policy.title),
                    ("Description", policy.description or ""),
                    ("Policy Type", policy.policy_type),
                    ("Status", policy.status),
                    ("Version", policy.version),
                    ("Content URL", policy.content_url or ""),
                    ("Owner User ID", str(policy.owner_user_id)),
                    ("Review Due Date", str(policy.review_due_date) if policy.review_due_date else ""),
                    ("Effective Date", str(policy.effective_date) if policy.effective_date else ""),
                    ("Created At", policy.created_at.isoformat()),
                    ("Updated At", policy.updated_at.isoformat()),
                ],
            )
        ]

        insights: list[str] = []
        today = datetime.now(UTC).date()
        if policy.archived_at is not None:
            insights.append("This policy is archived - do not present as current guidance.")
        if policy.review_due_date is not None and policy.review_due_date < today and policy.archived_at is None:
            days_overdue = (today - policy.review_due_date).days
            insights.append(
                f"Review is overdue by {days_overdue} day(s) (due {policy.review_due_date}) - "
                "content may no longer reflect current practice."
            )
        if policy.status == "draft" and policy.effective_date is not None and policy.effective_date <= today:
            insights.append(
                f"Effective date ({policy.effective_date}) has passed but the policy is still in draft status."
            )
        owner_flag = self._owner_insight(policy.owner_user_id)
        if owner_flag:
            insights.append(owner_flag)
        if insights:
            sections.append(ExportSection(title="Insights", items=insights))

        return ExportDocumentContent(
            organization_id=org_id,
            title=f"Compliance Policy Export: {policy.title}",
            subtitle=None,
            generated_at=self._now(),
            entity_type="compliance_policy",
            entity_id=policy.id,
            report_type=None,
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_control(self, org_id: uuid.UUID, control_id: uuid.UUID) -> ExportDocumentContent:
        control = ControlRepository(self.db).get_by_id(control_id)
        if control is None or control.organization_id != org_id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Control not found")
        sections = [
            ExportSection(
                title="Control",
                rows=[
                    ("Title", control.title),
                    ("Description", control.description or ""),
                    ("Control Code", control.control_code or ""),
                    ("Control Type", control.control_type),
                    ("Status", control.status),
                    ("Criticality", control.criticality),
                    ("Owner User ID", str(control.owner_user_id) if control.owner_user_id else ""),
                    ("Testing Procedure", control.testing_procedure or ""),
                    ("Implementation Notes", control.implementation_notes or ""),
                    ("Created At", control.created_at.isoformat()),
                    ("Updated At", control.updated_at.isoformat()),
                ],
            )
        ]

        insights: list[str] = []
        if control.criticality in {"high", "critical"} and control.status not in {"implemented", "effective"}:
            insights.append(
                f"Criticality is {control.criticality} but status is '{control.status}' - "
                "this control is not yet operating effectively."
            )
        if control.criticality in {"high", "critical"} and not (control.testing_procedure or "").strip():
            insights.append(
                f"Criticality is {control.criticality} but no testing procedure is documented."
            )
        owner_flag = self._owner_insight(control.owner_user_id)
        if owner_flag:
            insights.append(owner_flag)
        if insights:
            sections.append(ExportSection(title="Insights", items=insights))

        return ExportDocumentContent(
            organization_id=org_id,
            title=f"Control Export: {control.title}",
            subtitle=None,
            generated_at=self._now(),
            entity_type="control",
            entity_id=control.id,
            report_type=None,
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_risk(self, org_id: uuid.UUID, risk_id: uuid.UUID) -> ExportDocumentContent:
        risk = RiskRepository(self.db).get_by_id(risk_id)
        if risk is None or risk.organization_id != org_id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Risk not found")
        sections = [
            ExportSection(
                title="Risk",
                rows=[
                    ("Title", risk.title),
                    ("Description", risk.description or ""),
                    ("Category", risk.category),
                    ("Status", risk.status),
                    ("Severity", risk.severity),
                    ("Likelihood", str(risk.likelihood)),
                    ("Impact", str(risk.impact)),
                    ("Inherent Score", str(risk.inherent_score)),
                    ("Treatment Strategy", risk.treatment_strategy),
                    ("Owner User ID", str(risk.owner_user_id) if risk.owner_user_id else ""),
                    ("Created At", risk.created_at.isoformat()),
                    ("Updated At", risk.updated_at.isoformat()),
                ],
            )
        ]

        insights: list[str] = []
        now = datetime.now(UTC)
        if risk.review_due_at is not None:
            review_due = risk.review_due_at if risk.review_due_at.tzinfo else risk.review_due_at.replace(tzinfo=UTC)
            if review_due < now and risk.status not in {"closed", "accepted"}:
                insights.append(
                    f"Risk review is overdue (was due {review_due.isoformat()}) - "
                    "scoring may be stale."
                )
        if risk.residual_score is None:
            insights.append("Residual risk has not been assessed - only inherent risk is quantified here.")
        elif risk.residual_score >= risk.inherent_score:
            insights.append(
                "Residual score is not lower than inherent score - documented treatment has not "
                "measurably reduced this risk."
            )
        if (
            risk.treatment_strategy == "accept"
            and risk.severity in {"high", "critical"}
            and not risk.residual_risk_acceptable
        ):
            insights.append(
                f"Severity is {risk.severity} and treatment is 'accept' but there is no recorded "
                "acceptance sign-off (residual_risk_acceptable is not set)."
            )
        owner_flag = self._owner_insight(risk.owner_user_id)
        if owner_flag:
            insights.append(owner_flag)
        if insights:
            sections.append(ExportSection(title="Insights", items=insights))

        return ExportDocumentContent(
            organization_id=org_id,
            title=f"Risk Export: {risk.title}",
            subtitle=None,
            generated_at=self._now(),
            entity_type="risk",
            entity_id=risk.id,
            report_type=None,
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_vendor(self, org_id: uuid.UUID, vendor_id: uuid.UUID) -> ExportDocumentContent:
        vendor = VendorService(self.db).require_vendor_in_org(org_id, vendor_id)
        sections = [
            ExportSection(
                title="Vendor",
                rows=[
                    ("Name", vendor.name),
                    ("Description", vendor.description or ""),
                    ("Vendor Type", vendor.vendor_type),
                    ("Website", vendor.website or ""),
                    ("Primary Contact Name", vendor.primary_contact_name or ""),
                    ("Primary Contact Email", vendor.primary_contact_email or ""),
                    ("Risk Tier", vendor.risk_tier),
                    ("Status", vendor.status),
                    ("Owner User ID", str(vendor.owner_user_id)),
                    ("Created At", vendor.created_at.isoformat()),
                    ("Updated At", vendor.updated_at.isoformat()),
                ],
            )
        ]

        insights: list[str] = []
        if vendor.risk_tier == "not_assessed" and (vendor.data_access or vendor.processes_personal_data):
            insights.append(
                "Vendor has data access or processes personal data but has not been risk-assessed."
            )
        if vendor.nth_party_risk_flag:
            severity = vendor.nth_party_risk_severity or "unspecified"
            insights.append(f"Nth-party risk signal flagged (severity: {severity}) - review sub-processor chain.")
        if vendor.sub_processor and vendor.risk_tier in {"not_assessed", "low"}:
            insights.append(
                "Vendor relies on sub-processors but is rated low/not-assessed risk - "
                "verify sub-processor due diligence coverage."
            )
        owner_flag = self._owner_insight(vendor.owner_user_id)
        if owner_flag:
            insights.append(owner_flag)
        if insights:
            sections.append(ExportSection(title="Insights", items=insights))

        return ExportDocumentContent(
            organization_id=org_id,
            title=f"Vendor Export: {vendor.name}",
            subtitle=None,
            generated_at=self._now(),
            entity_type="vendor",
            entity_id=vendor.id,
            report_type=None,
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_posture_report(self, org_id: uuid.UUID) -> ExportDocumentContent:
        payload = ComplianceDashboardService(self.db).posture_summary(org_id)
        sections = [
            ExportSection(
                title="Compliance Posture Summary",
                rows=self._to_rows(payload),
            )
        ]
        return ExportDocumentContent(
            organization_id=org_id,
            title="Compliance Posture Report",
            subtitle="Generated from dashboard posture summary",
            generated_at=self._now(),
            entity_type="report",
            entity_id=None,
            report_type="posture",
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_framework_coverage_report(self, org_id: uuid.UUID) -> ExportDocumentContent:
        payload = ComplianceDashboardService(self.db).framework_readiness(org_id)
        rows: list[tuple[str, str]] = []
        for item in payload:
            name = item.get("name", "Framework")
            coverage = item.get("control_coverage_pct")
            evidence = item.get("evidence_verified_pct")
            gaps = item.get("open_gaps_count")
            rows.append((str(name), f"Coverage {coverage}% | Evidence {evidence}% | Open gaps {gaps}"))
        sections = [
            ExportSection(
                title="Framework Coverage",
                rows=rows,
                items=[f"Total frameworks: {len(payload)}"],
            )
        ]
        return ExportDocumentContent(
            organization_id=org_id,
            title="Framework Coverage Report",
            subtitle="Generated from compliance framework readiness",
            generated_at=self._now(),
            entity_type="report",
            entity_id=None,
            report_type="framework_coverage",
            branding=self._branding(org_id),
            sections=sections,
        )

    def build_board_scorecard(self, snapshot: BoardScorecardSnapshot) -> ExportDocumentContent:
        data = snapshot.snapshot_data if isinstance(snapshot.snapshot_data, dict) else {}
        scope = data.get("scope", {}) if isinstance(data.get("scope"), dict) else {}
        sections = [
            ExportSection(
                title="Board Scorecard Summary",
                rows=[
                    ("Snapshot Label", snapshot.snapshot_label or ""),
                    ("Overall Compliance Score", str(snapshot.overall_compliance_score)),
                    ("Organization ID", str(snapshot.organization_id)),
                    ("Business Unit ID", str(snapshot.business_unit_id) if snapshot.business_unit_id else "org-wide"),
                    ("Generated By", str(snapshot.generated_by)),
                    ("Created At", snapshot.created_at.isoformat() if snapshot.created_at else ""),
                ],
                paragraphs=[
                    f"Scope: organization {scope.get('organization_id', str(snapshot.organization_id))}",
                    (
                        f"Business unit: {scope.get('business_unit_name') or scope.get('business_unit_id')}"
                        if scope.get("business_unit_id")
                        else "Business unit: org-wide"
                    ),
                ],
            ),
            ExportSection(
                title="Posture Summary",
                rows=self._to_rows(data.get("posture_summary", {}) if isinstance(data.get("posture_summary"), dict) else {}),
            ),
            ExportSection(
                title="Framework Readiness",
                rows=self._to_rows(data.get("framework_readiness", {}) if isinstance(data.get("framework_readiness"), dict) else {}),
            ),
            ExportSection(
                title="Top Risk Signals",
                rows=self._to_rows(data.get("top_risks", {}) if isinstance(data.get("top_risks"), dict) else {}),
            ),
            ExportSection(
                title="Risk Appetite Breaches",
                rows=self._to_rows(data.get("risk_appetite_breaches", {}) if isinstance(data.get("risk_appetite_breaches"), dict) else {}),
            ),
            ExportSection(
                title="Control Effectiveness",
                rows=self._to_rows(data.get("control_effectiveness", {}) if isinstance(data.get("control_effectiveness"), dict) else {}),
            ),
            ExportSection(
                title="Compliance Deadlines",
                rows=self._to_rows(data.get("deadlines", {}) if isinstance(data.get("deadlines"), dict) else {}),
            ),
            ExportSection(
                title="KRI Summary",
                rows=self._to_rows(data.get("kri_summary", {}) if isinstance(data.get("kri_summary"), dict) else {}),
            ),
        ]
        return ExportDocumentContent(
            organization_id=snapshot.organization_id,
            title="Board Scorecard Snapshot",
            subtitle=f"Snapshot ID: {snapshot.id}",
            generated_at=self._now(),
            entity_type="board_scorecard_snapshot",
            entity_id=snapshot.id,
            report_type="board_scorecard",
            branding=self._branding(snapshot.organization_id),
            sections=sections,
        )

    def build_ai_governance_diagnostic(self, snapshot: AIGovernanceDiagnosticSnapshot) -> ExportDocumentContent:
        data = snapshot.snapshot_data if isinstance(snapshot.snapshot_data, dict) else {}
        scope = data.get("scope", {}) if isinstance(data.get("scope"), dict) else {}
        sections = [
            ExportSection(
                title="AI Governance Diagnostic Summary",
                rows=[
                    ("Snapshot Label", snapshot.snapshot_label or ""),
                    ("Overall Governance Score", str(snapshot.overall_governance_score)),
                    ("Overall Health", snapshot.overall_health),
                    ("AI Systems Assessed", str(snapshot.ai_systems_assessed)),
                    ("Critical Gaps Count", str(snapshot.critical_gaps_count)),
                    ("Organization ID", str(snapshot.organization_id)),
                    ("Business Unit ID", str(snapshot.business_unit_id) if snapshot.business_unit_id else "org-wide"),
                    ("Generated By", str(snapshot.generated_by)),
                    ("Created At", snapshot.created_at.isoformat() if snapshot.created_at else ""),
                ],
                paragraphs=[
                    f"Scope organization: {scope.get('organization_id', str(snapshot.organization_id))}",
                    (
                        f"Scope business unit: {scope.get('business_unit_name') or scope.get('business_unit_id')}"
                        if scope.get("business_unit_id")
                        else "Scope business unit: org-wide"
                    ),
                ],
            ),
            ExportSection(
                title="Organization Level Summary",
                rows=self._to_rows(data.get("org_level_summary", {}) if isinstance(data.get("org_level_summary"), dict) else {}),
            ),
            ExportSection(
                title="AI Systems Detail",
                rows=self._to_rows({"systems": data.get("ai_systems_summary", [])}),
            ),
            ExportSection(
                title="Posture Summary",
                rows=self._to_rows(data.get("posture_summary", {}) if isinstance(data.get("posture_summary"), dict) else {}),
            ),
        ]
        return ExportDocumentContent(
            organization_id=snapshot.organization_id,
            title="AI Governance Diagnostic Snapshot",
            subtitle=f"Snapshot ID: {snapshot.id}",
            generated_at=self._now(),
            entity_type="ai_governance_diagnostic_snapshot",
            entity_id=snapshot.id,
            report_type="ai_governance_diagnostic",
            branding=self._branding(snapshot.organization_id),
            sections=sections,
        )

    def build_audit_evidence_package(
        self,
        org_id: uuid.UUID,
        audit_id: uuid.UUID,
        framework_id: uuid.UUID | None = None,
    ) -> ExportDocumentContent:
        engagement = (
            self.db.query(AuditEngagement)
            .filter(
                AuditEngagement.organization_id == org_id,
                AuditEngagement.id == audit_id,
                AuditEngagement.deleted_at.is_(None),
            )
            .first()
        )
        if engagement is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Audit engagement not found")

        scoped_framework_id: uuid.UUID | None = framework_id
        if scoped_framework_id is None and engagement.scope_framework_ids:
            try:
                scoped_framework_id = uuid.UUID(str(engagement.scope_framework_ids[0]))
            except (ValueError, TypeError):
                scoped_framework_id = None

        framework_name: str | None = None
        if scoped_framework_id is not None:
            fw = self.db.query(Framework).filter(Framework.id == scoped_framework_id).first()
            framework_name = fw.name if fw else None

        # Obligations belong to the (org-agnostic) framework catalog, not to a per-org row --
        # scope by the org's ACTIVE framework(s) rather than requiring an
        # OrganizationObligationState row, which only exists once a user has individually
        # reviewed that specific obligation (most obligations under a freshly-activated
        # framework never get one, and previously made this export silently show zero
        # obligations/controls/evidence despite real coverage existing).
        obligation_query = (
            self.db.query(Obligation)
            .join(OrganizationFramework, OrganizationFramework.framework_id == Obligation.framework_id)
            .filter(
                OrganizationFramework.organization_id == org_id,
                OrganizationFramework.status == "active",
            )
        )
        if scoped_framework_id is not None:
            obligation_query = obligation_query.filter(Obligation.framework_id == scoped_framework_id)
        obligations = obligation_query.order_by(Obligation.reference_code.asc(), Obligation.title.asc()).all()

        sections: list[ExportSection] = []
        total_obligations = len(obligations)
        obligations_with_verified = 0
        total_controls = 0
        controls_with_verified = 0
        total_evidence_items = 0

        for obligation in obligations:
            linked_controls = (
                self.db.query(Control)
                .outerjoin(
                    ControlObligationMapping,
                    (ControlObligationMapping.organization_id == org_id)
                    & (ControlObligationMapping.control_id == Control.id)
                    & (ControlObligationMapping.obligation_id == obligation.id)
                    & (ControlObligationMapping.status == "active"),
                )
                .filter(Control.organization_id == org_id)
                .filter(
                    (Control.obligation_id == obligation.id) | (ControlObligationMapping.id.is_not(None))
                )
                .order_by(Control.title.asc())
                .all()
            )

            control_lines: list[str] = []
            has_verified_for_obligation = False
            for control in linked_controls:
                total_controls += 1
                evidence_rows = (
                    self.db.query(EvidenceItem)
                    .join(EvidenceControlLink, EvidenceControlLink.evidence_item_id == EvidenceItem.id)
                    .filter(
                        EvidenceControlLink.organization_id == org_id,
                        EvidenceControlLink.control_id == control.id,
                        EvidenceControlLink.link_status == "active",
                        EvidenceItem.organization_id == org_id,
                        EvidenceItem.review_status == "verified",
                    )
                    .order_by(EvidenceItem.updated_at.desc())
                    .all()
                )
                if evidence_rows:
                    has_verified_for_obligation = True
                    controls_with_verified += 1
                total_evidence_items += len(evidence_rows)
                evidence_lines = [
                    (
                        f"- {item.title} | source={item.source} | "
                        f"verified_at={(item.reviewed_at.isoformat() if item.reviewed_at else item.updated_at.isoformat())}"
                    )
                    for item in evidence_rows
                ]
                control_lines.append(
                    f"Control: {control.title} | status={control.status} | verified_evidence={len(evidence_rows)}"
                )
                control_lines.extend(evidence_lines)

            if has_verified_for_obligation:
                obligations_with_verified += 1

            obligation_ref = obligation.reference_code or str(obligation.id)
            sections.append(
                ExportSection(
                    title=f"{obligation_ref} - {obligation.title}",
                    items=control_lines,
                )
            )

        coverage_pct = round((obligations_with_verified / total_obligations) * 100, 2) if total_obligations else 0.0

        summary_rows = [
            ("Audit Title", engagement.title),
            ("Audit Status", engagement.status),
            ("Framework", framework_name or "All"),
            ("Total Obligations", str(total_obligations)),
            ("Obligations With Verified Evidence", str(obligations_with_verified)),
            ("Total Controls", str(total_controls)),
            ("Controls With Verified Evidence", str(controls_with_verified)),
            ("Total Evidence Items", str(total_evidence_items)),
            ("Coverage Percent", f"{coverage_pct}"),
        ]
        sections.insert(0, ExportSection(title="Evidence Package Summary", rows=summary_rows))

        return ExportDocumentContent(
            organization_id=org_id,
            title=f"Audit Evidence Package: {engagement.title}",
            subtitle=f"Audit ID: {engagement.id}",
            generated_at=self._now(),
            entity_type="audit_engagement",
            entity_id=engagement.id,
            report_type="audit_evidence_package",
            branding=self._branding(org_id),
            sections=sections,
        )
