"""Pillar 2 routers."""

from app.ai_governance.routers import (
    atlas,
    approval_envelopes,
    ai_reviews,
    ai_risk_assessments,
    ai_systems,
    eu_act_workflows,
    guardrails,
    iso42001,
    risk_signals,
    recommendations,
    diagnostics,
    ai_governance_diagnostics,
    contracts,
    monitoring,
    mlops,
    mlops_ingest,
    mlops_management,
    nist_rmf,
    policy_derivation,
    shadow_ai,
    third_party_ai,
)

__all__ = [
    "atlas",
    "approval_envelopes",
    "ai_reviews",
    "ai_risk_assessments",
    "ai_systems",
    "eu_act_workflows",
    "guardrails",
    "iso42001",
    "risk_signals",
    "recommendations",
    "diagnostics",
    "ai_governance_diagnostics",
    "contracts",
    "monitoring",
    "mlops",
    "mlops_ingest",
    "mlops_management",
    "nist_rmf",
    "policy_derivation",
    "shadow_ai",
    "third_party_ai",
]
