from __future__ import annotations

import uuid
import hashlib
from datetime import UTC, datetime
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.deps import get_current_active_user, get_current_organization, get_db, require_permission
from app.exports.schemas.export_settings import ExportSettingsRead, ExportSettingsUpdate
from app.exports.services.docx_renderer import DocxRenderer
from app.exports.services.export_content_builder import ExportContentBuilder
from app.exports.services.pdf_renderer import PDFRenderer
from app.models.membership import Membership
from app.models.organization import Organization
from app.models.organization_export_setting import OrganizationExportSetting
from app.models.role import Role
from app.models.user import User
from app.services.audit_service import AuditService

router = APIRouter(tags=["entity-exports"])
SETTINGS_STALE_AFTER_DAYS = 180


def _require_org_admin(db: Session, membership: Membership) -> None:
    role = db.execute(select(Role).where(Role.id == membership.role_id)).scalar_one_or_none()
    if role is None or role.name not in {"owner", "admin"}:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Org admin role required")


def _render(content, export_format: Literal["pdf", "docx"]) -> tuple[bytes, str, str]:
    if export_format == "pdf":
        rendered = PDFRenderer().render(content)
        return rendered, "application/pdf", "pdf"
    rendered = DocxRenderer().render(content)
    return (
        rendered,
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "docx",
    )


def _stream_file(data: bytes, media_type: str, filename: str, *, checksum_sha256: str, context_flags: list[str]) -> StreamingResponse:
    return StreamingResponse(
        iter([data]),
        media_type=media_type,
        headers={
            "Content-Disposition": f"attachment; filename={filename}",
            "X-Export-Checksum-SHA256": checksum_sha256,
            "X-Export-Bytes": str(len(data)),
            "X-Export-Context-Flags": ",".join(context_flags),
        },
    )


def _write_export_audit(
    *,
    db: Session,
    organization_id: uuid.UUID,
    actor_user_id: uuid.UUID,
    entity_type: str,
    entity_id: uuid.UUID | None,
    export_format: str,
    report_type: str | None = None,
    byte_size: int,
    checksum_sha256: str,
    context_flags: list[str],
    request: Request,
) -> None:
    AuditService(db).write_audit_log(
        action="export.generated",
        entity_type=entity_type,
        entity_id=entity_id,
        organization_id=organization_id,
        actor_user_id=actor_user_id,
        after_json={
            "format": export_format,
            "byte_size": byte_size,
            "checksum_sha256": checksum_sha256,
            "context_flags": context_flags,
        },
        metadata_json={
            "format": export_format,
            "report_type": report_type,
        },
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )


def _render_with_telemetry(content, export_format: Literal["pdf", "docx"]) -> tuple[bytes, str, str, str, list[str]]:
    rendered, media_type, extension = _render(content, export_format)
    checksum_sha256 = hashlib.sha256(rendered).hexdigest()
    context_flags = sorted(set(getattr(content, "context_flags", []) or []))
    return rendered, media_type, extension, checksum_sha256, context_flags


def _settings_context(row: OrganizationExportSetting | None, organization: Organization) -> dict:
    now = datetime.now(UTC)
    is_default = row is None
    updated_at = row.updated_at if row is not None else None
    if updated_at is not None and updated_at.tzinfo is None:
        updated_at = updated_at.replace(tzinfo=UTC)
    is_stale = bool(updated_at and (now - updated_at).days > SETTINGS_STALE_AFTER_DAYS)

    company_name = (row.company_display_name if row else organization.name) or organization.name
    logo_url = row.logo_url if row else None
    footer_text = row.footer_text if row else "Generated by CompliVibe"
    primary_color_hex = row.primary_color_hex if row else "#1F4B99"

    context_flags: list[str] = []
    if is_default:
        context_flags.append("default_branding_in_use")
    if is_stale:
        context_flags.append("branding_configuration_stale")
    if not logo_url:
        context_flags.append("branding_logo_missing")
    if company_name == organization.name:
        context_flags.append("branding_uses_org_name")
    if not footer_text:
        context_flags.append("branding_footer_missing")
    if not primary_color_hex:
        context_flags.append("branding_color_missing")

    return {
        "is_default": is_default,
        "is_stale": is_stale,
        "context_flags": context_flags,
    }


@router.get("/compliance/policies/{policy_id}/export")
def export_policy(
    policy_id: uuid.UUID,
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("compliance_policies:read")),
):
    content = ExportContentBuilder(db).build_policy(organization.id, policy_id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="compliance_policy",
        entity_id=policy_id,
        export_format=format,
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"policy_{policy_id}.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/compliance/controls/{control_id}/export")
def export_control(
    control_id: uuid.UUID,
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("controls:read")),
):
    content = ExportContentBuilder(db).build_control(organization.id, control_id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="control",
        entity_id=control_id,
        export_format=format,
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"control_{control_id}.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/risks/{risk_id}/export")
def export_risk(
    risk_id: uuid.UUID,
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("risks:read")),
):
    content = ExportContentBuilder(db).build_risk(organization.id, risk_id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="risk",
        entity_id=risk_id,
        export_format=format,
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"risk_{risk_id}.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/vendors/{vendor_id}/export")
def export_vendor(
    vendor_id: uuid.UUID,
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("vendors:read")),
):
    content = ExportContentBuilder(db).build_vendor(organization.id, vendor_id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="vendor",
        entity_id=vendor_id,
        export_format=format,
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"vendor_{vendor_id}.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/compliance/reports/posture/export")
def export_posture_report(
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("compliance_policies:read")),
):
    content = ExportContentBuilder(db).build_posture_report(organization.id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="compliance_report",
        entity_id=None,
        export_format=format,
        report_type="posture",
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"posture_report.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/compliance/reports/framework-coverage/export")
def export_framework_coverage_report(
    request: Request,
    format: Literal["pdf", "docx"] = Query(default="pdf"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    _: Membership = Depends(require_permission("compliance_policies:read")),
):
    content = ExportContentBuilder(db).build_framework_coverage_report(organization.id)
    rendered, media_type, extension, checksum_sha256, context_flags = _render_with_telemetry(content, format)
    _write_export_audit(
        db=db,
        organization_id=organization.id,
        actor_user_id=current_user.id,
        entity_type="compliance_report",
        entity_id=None,
        export_format=format,
        report_type="framework_coverage",
        byte_size=len(rendered),
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
        request=request,
    )
    db.commit()
    return _stream_file(
        rendered,
        media_type,
        f"framework_coverage_report.{extension}",
        checksum_sha256=checksum_sha256,
        context_flags=context_flags,
    )


@router.get("/organizations/export-settings", response_model=ExportSettingsRead)
def get_export_settings(
    db: Session = Depends(get_db),
    organization: Organization = Depends(get_current_organization),
    membership: Membership = Depends(require_permission("compliance:read")),
):
    _require_org_admin(db, membership)
    row = (
        db.query(OrganizationExportSetting)
        .filter(OrganizationExportSetting.organization_id == organization.id)
        .first()
    )
    if row is None:
        context = _settings_context(None, organization)
        return ExportSettingsRead(
            id=None,
            organization_id=organization.id,
            logo_url=None,
            company_display_name=organization.name,
            footer_text="Generated by CompliVibe",
            primary_color_hex="#1F4B99",
            is_default=context["is_default"],
            is_stale=context["is_stale"],
            context_flags=context["context_flags"],
            created_at=None,
            updated_at=None,
        )
    context = _settings_context(row, organization)
    return ExportSettingsRead(
        id=row.id,
        organization_id=row.organization_id,
        logo_url=row.logo_url,
        company_display_name=row.company_display_name or organization.name,
        footer_text=row.footer_text,
        primary_color_hex=row.primary_color_hex,
        is_default=context["is_default"],
        is_stale=context["is_stale"],
        context_flags=context["context_flags"],
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


@router.put("/organizations/export-settings", response_model=ExportSettingsRead)
def upsert_export_settings(
    payload: ExportSettingsUpdate,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
    organization: Organization = Depends(get_current_organization),
    membership: Membership = Depends(require_permission("compliance:write")),
):
    _require_org_admin(db, membership)
    row = (
        db.query(OrganizationExportSetting)
        .filter(OrganizationExportSetting.organization_id == organization.id)
        .first()
    )
    if row is None:
        row = OrganizationExportSetting(
            organization_id=organization.id,
            logo_url=payload.logo_url,
            company_display_name=payload.company_display_name,
            footer_text=payload.footer_text,
            primary_color_hex=payload.primary_color_hex,
        )
        db.add(row)
        changed = True
    else:
        changed = any(
            [
                row.logo_url != payload.logo_url,
                row.company_display_name != payload.company_display_name,
                row.footer_text != payload.footer_text,
                row.primary_color_hex != payload.primary_color_hex,
            ]
        )
        if changed:
            row.logo_url = payload.logo_url
            row.company_display_name = payload.company_display_name
            row.footer_text = payload.footer_text
            row.primary_color_hex = payload.primary_color_hex
            row.updated_at = datetime.now(UTC)

    if changed:
        db.flush()
        AuditService(db).write_audit_log(
            action="organization.export_settings_updated",
            entity_type="organization_export_settings",
            entity_id=row.id,
            organization_id=organization.id,
            actor_user_id=current_user.id,
            metadata_json={"source": "api"},
            ip_address=request.client.host if request and request.client else None,
            user_agent=request.headers.get("user-agent") if request else None,
        )
        db.commit()
    else:
        db.rollback()
        row = (
            db.query(OrganizationExportSetting)
            .filter(OrganizationExportSetting.organization_id == organization.id)
            .first()
        )
        if row is None:
            # No persisted row existed and payload matched defaults.
            return ExportSettingsRead(
                id=None,
                organization_id=organization.id,
                logo_url=None,
                company_display_name=organization.name,
                footer_text="Generated by CompliVibe",
                primary_color_hex="#1F4B99",
                is_default=True,
                is_stale=False,
                context_flags=["default_branding_in_use", "branding_logo_missing", "branding_uses_org_name"],
                created_at=None,
                updated_at=None,
            )

    db.refresh(row)
    context = _settings_context(row, organization)

    return ExportSettingsRead(
        id=row.id,
        organization_id=row.organization_id,
        logo_url=row.logo_url,
        company_display_name=row.company_display_name or organization.name,
        footer_text=row.footer_text,
        primary_color_hex=row.primary_color_hex,
        is_default=context["is_default"],
        is_stale=context["is_stale"],
        context_flags=context["context_flags"],
        created_at=row.created_at,
        updated_at=row.updated_at,
    )
