from __future__ import annotations

from io import BytesIO
from uuid import UUID

from sqlalchemy import inspect, select

from app.exports.services.export_content_builder import ExportContentBuilder
from app.exports.services.pdf_renderer import PDFRenderer
from app.models.audit_log import AuditLog
from app.models.compliance_policy import CompliancePolicy
from app.models.control import Control
from app.models.organization_export_setting import OrganizationExportSetting
from app.models.risk import Risk
from app.models.vendor import Vendor
from tests.helpers.auth_org import bootstrap_org_user


def test_entity_pdf_docx_exports_and_audit_log(client, db_session):
    owner = bootstrap_org_user(client, email_prefix="export-owner")
    headers = owner["org_headers"]
    org_id = UUID(owner["organization_id"])
    user_id = UUID(owner["user_id"])

    policy = CompliancePolicy(
        organization_id=org_id,
        title="Exportable Policy",
        policy_type="security",
        owner_user_id=user_id,
    )
    db_session.add(policy)
    db_session.flush()

    pdf_resp = client.get(f"/api/v1/compliance/policies/{policy.id}/export?format=pdf", headers=headers)
    assert pdf_resp.status_code == 200, pdf_resp.text
    assert pdf_resp.headers["content-type"].startswith("application/pdf")
    assert len(pdf_resp.content) > 20
    assert pdf_resp.content[:4] == b"%PDF"

    docx_resp = client.get(f"/api/v1/compliance/policies/{policy.id}/export?format=docx", headers=headers)
    assert docx_resp.status_code == 200, docx_resp.text
    assert docx_resp.headers["content-type"].startswith(
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    assert len(docx_resp.content) > 50
    assert docx_resp.content[:2] == b"PK"

    audit = (
        db_session.execute(
            select(AuditLog).where(
                AuditLog.organization_id == org_id,
                AuditLog.action == "export.generated",
                AuditLog.entity_type == "compliance_policy",
                AuditLog.entity_id == policy.id,
            )
        )
        .scalars()
        .first()
    )
    assert audit is not None
    assert audit.metadata_json.get("format") in {"pdf", "docx"}


def test_branding_applied_and_default_fallback(client, db_session):
    owner = bootstrap_org_user(client, email_prefix="export-brand")
    org_id = UUID(owner["organization_id"])

    builder = ExportContentBuilder(db_session)

    default_content = builder.build_posture_report(org_id)
    default_html = PDFRenderer().build_html(default_content)
    assert "#1F4B99" in default_html
    assert "Generated by CompliVibe" in default_html

    custom = OrganizationExportSetting(
        organization_id=org_id,
        company_display_name="Acme Compliance",
        logo_url="https://cdn.example.com/acme.png",
        footer_text="Confidential - Internal Use",
        primary_color_hex="#AA1133",
    )
    db_session.add(custom)
    db_session.flush()

    branded_content = builder.build_posture_report(org_id)
    branded_html = PDFRenderer().build_html(branded_content)
    assert "Acme Compliance" in branded_html
    assert "#AA1133" in branded_html
    assert "Confidential - Internal Use" in branded_html
    assert "acme.png" in branded_html


def test_cross_org_export_rejected(client, db_session):
    org_a = bootstrap_org_user(client, email_prefix="export-a")
    org_b = bootstrap_org_user(client, email_prefix="export-b")

    org_a_id = UUID(org_a["organization_id"])
    user_a_id = UUID(org_a["user_id"])

    risk = Risk(organization_id=org_a_id, title="Org A Risk", created_by_user_id=user_a_id)
    db_session.add(risk)
    db_session.flush()

    denied = client.get(f"/api/v1/risks/{risk.id}/export?format=pdf", headers=org_b["org_headers"])
    assert denied.status_code == 404


def test_report_level_exports_succeed(client, db_session):
    owner = bootstrap_org_user(client, email_prefix="export-report")
    headers = owner["org_headers"]
    org_id = UUID(owner["organization_id"])
    user_id = UUID(owner["user_id"])

    control = Control(organization_id=org_id, title="C1", created_by_user_id=user_id)
    vendor = Vendor(organization_id=org_id, name="Vendor 1", vendor_type="processor", owner_user_id=user_id)
    db_session.add_all([control, vendor])
    db_session.flush()

    posture = client.get("/api/v1/compliance/reports/posture/export?format=pdf", headers=headers)
    assert posture.status_code == 200, posture.text
    assert posture.content[:4] == b"%PDF"

    coverage = client.get("/api/v1/compliance/reports/framework-coverage/export?format=docx", headers=headers)
    assert coverage.status_code == 200, coverage.text
    assert coverage.content[:2] == b"PK"


def test_export_settings_endpoint_admin_only_and_table_exists(client, db_session):
    inspector = inspect(db_session.bind)
    assert "organization_export_settings" in set(inspector.get_table_names())

    owner = bootstrap_org_user(client, email_prefix="export-settings")
    headers = owner["org_headers"]

    get_default = client.get("/api/v1/organizations/export-settings", headers=headers)
    assert get_default.status_code == 200
    assert get_default.json()["primary_color_hex"] == "#1F4B99"

    put_resp = client.put(
        "/api/v1/organizations/export-settings",
        headers=headers,
        json={
            "company_display_name": "New Name",
            "footer_text": "Footer",
            "primary_color_hex": "#112233",
        },
    )
    assert put_resp.status_code == 200, put_resp.text
    body = put_resp.json()
    assert body["company_display_name"] == "New Name"
    assert body["primary_color_hex"] == "#112233"
